### ISSUE TITLE
Layers are hard to drag

### ISSUE THREAD

**Issue by dsizzle** [HaikuArchives/ArtPaint#109]
The UI for Layers doesn't leave a lot of room to grab and drag to re-order. 
- grabbing the thumbnail and dropping on the canvas creates a duplicate layer.  Is it possible to use that same drag functionality within the Layer window for reordering? Is dragging a layer onto the canvas to duplicate the layer an intuitive action? 
- the dropdown for adding, deleting, and merging layers could be moved to a single toolbar/menu so it doesn't take up space in each layer, and therefore would make reordering easier

reference of Photoshop's Layer panel; taken from photoshopcafe.com:
![pshop-layers](https://user-images.githubusercontent.com/10878750/161452829-b219ebfa-1bda-42ff-8de7-ec2cfc67cbef.png)

**Comment by humdingerb** [comment]
> grabbing the thumbnail and dropping on the canvas creates a duplicate layer. Is it possible to use that same drag functionality within the Layer window for reordering?

Sure. See e.g. the "Shape" list in Icon-O-Matic or the list of "Preferred languages" in the Locale prefs. Or the list of favourites of QuickLaunch.

> Is dragging a layer onto the canvas to duplicate the layer an intuitive action?

Not to me...

> the dropdown for adding, deleting, and merging layers could be moved to a single 
 toolbar/menu

+1, leaves space for an opacity setting (maybe like the main window's magnification, i.e. a slider that pops up when clicked on. Also for a blending mode menu ("lighten/darken/alpha/whatever) someday. 
IMO, the combined-layers-preview at the top of the Layers window  could be removed as well: You see all the separate layers below it anyway, plus on the main window's canvas itself.
Maybe I should create tickets for the above...

**Comment by dsizzle** [comment]
> > Is it possible to use that same drag functionality within the Layer window for reordering?

>Sure. See e.g. the "Shape" list in Icon-O-Matic or the list of "Preferred languages" in the Locale prefs. Or the list of favourites of QuickLaunch.

Sorry - dragging already works, but what I meant was if dragging the thumbnail itself could have different behavior depending on whether it was dropped on the layer window or the main window.  

but, given this:

> >  Is dragging a layer onto the canvas to duplicate the layer an intuitive action?

> Not to me...

I am inclined to just eliminate that thumbnail drag so that the entire layer can be grabbed a lot more easily.  

> IMO, the combined-layers-preview at the top of the Layers window could be removed as well: You see all the separate layers below it anyway, plus on the main window's canvas itself.

I agree. I can't find any benefit to having the composite thumbnail.  In a complex, multi-layered image, it would just be another copy of the main window to render.  It doesn't add anything for me.

**Comment by humdingerb** [comment]
+1

**Comment by humdingerb** [comment]
Fixed with 506db22d799469b84f5dd7565be9382a03594981
