### ISSUE TITLE
Selection tool works 'inverted'

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#117]
If you make a selection, you can touch all pixels _outside_ that selection, not as expected only the pixels within.

**Comment by dsizzle** [comment]
I can't reproduce this. My selections seem to properly contain the pixels I want them to. Do you have steps to repro?

**Comment by humdingerb** [comment]
Arrgh... user mistake. The mode for the selection tool in the tool setup was on "Substract area"... With "Add area" it works as expected.

I'm used to "SHIFT + select" to add to the selection and "CTRL + select" to substract from the selection...
Sorry for the noise.

**Comment by dsizzle** [comment]
Hey, I'll take not-bugs over bugs any day. 😆 

Can you also close #5 ? I think the Selector tool seems to work as much as I've tested it.
