### ISSUE TITLE
Selection: alpha is not respected for selections in Layer mode

### ISSUE THREAD

**Issue by dsizzle** [HaikuArchives/ArtPaint#120]
Select an area like this:
![select-alpha01](https://user-images.githubusercontent.com/10878750/162060263-736f1b1a-2e42-4903-af56-1a1ec751bf6d.png)

...then use Layer->Translate:
![select-alpha02](https://user-images.githubusercontent.com/10878750/162060392-6ffb42a9-60da-4a6b-8e57-ea69c39c6953.png)

...the background of the selection is white, when it should be transparent.  In this instance the red stroke should also be translucent.

**Comment by humdingerb** [comment]
It'd be nice if transparent areas were light/dark grey checkered, like in I-O-M or WonderBrush. Being just white, it's quite confusing.

**Comment by dsizzle** [comment]
Yes. I have actually been working on that for the past few days because I know that's something Pete was trying to do (and yeah, other tools do the same). That's when I discovered this and wanted to see if it was my alpha checkerboard that broke it.
