### ISSUE TITLE
Support common modifier key functions

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#126]
There are some modifier key functions that are commonly used by graphics apps:

* +CTRL:
    * lock aspect ratio to create circles and squares (already does for rect/ellipses tools)
    * draw lines with a 0°/45°/90° angle (already does for straight line tool)
    * rotate by 0°/45°/90° angle
    * keep aspect ratio when resizing something
    * add to a selection
 * +SHIFT:
    * remove from a selection
* +ALT:
    * when creting an ellipse or rectangle or when selecting, take the point where the mouse button was pressed as center. (Some tools - e.g. Rectangle tool - already have that option as "Center to corner" instead of the usual "Corner to corner)
    * with mouse wheel-up: zoom in (formerly #96)
    * with mouse wheel-down: zoom out (formerly #96)

**Comment by dsizzle** [comment]
I think these are good ideas. 

One question I have is, what is the behavior when a modifier key conflicts with the chosen option?  I assume the key modifier should override the option, but does the option change temporarily to reflect the key press?

**Comment by Lt-Henry** [comment]
Issue #96 can be merged here. Don't you think?

**Comment by humdingerb** [comment]
> One question I have is, what is the behavior when a modifier key conflicts with the chosen option? I assume the key modifier should override the option, but does the option change temporarily to reflect the key press?

IMO, once these modifier behaviours are implemented, the options should be removed from the tool setup menus. It's most consistent and the result will always be predictable. Otherwise ALT or SHIFT can do different things with different tools if their options are toggled differently. Chaos! :)

**Comment by dsizzle** [comment]
ugh. These might be super easy to do (at least I tried ellipse) but it makes #32 MUCH worse when you switch between the "center" mode and "corner-to-corner" mode. gray lines everywhere! :(

also turns out Alt is some kind of 'eyedropper' shortcut that grabs the color under the cursor.  That would need to be disabled or remapped.

**Comment by Brunobasta** [comment]
shift +i (to inverse the selection is a very handy shortcut)

**Comment by Brunobasta** [comment]
I agree with hundingers modifier key functions

**Comment by dsizzle** [comment]
these are all done now, yes?

**Comment by humdingerb** [comment]
Tools wise, yes. Only modifier relates feature still missing seems to be the SHIFT snaps rotation to 22,5° angles for the rotation of canvas and layer.
