### ISSUE TITLE
Tools with a "size" setting should draw a circle showing the size

### ISSUE THREAD

**Issue by dsizzle** [HaikuArchives/ArtPaint#128]
...especially since there's already a setting for "crosshair cursor" vs "tool cursor", any tool with a size setting should show what that size looks like on the canvas for the "tool cursor" option.

**Comment by dsizzle** [comment]
Just putting a note here in case I forget: 
Can we leverage Selection::SimplifySelection() to generate a polygon representation of any arbitrary brush shape? That’d be much nicer than just a circle or square showing the size.

**Comment by humdingerb** [comment]
There's are outline artifacts when testing #536, best seen when disabling "Use current brush" and a size of around 50:

![ezgif-5-ccf49ecd2b](https://github.com/HaikuArchives/ArtPaint/assets/6107158/7826c0e4-f6b2-45af-ba6b-3f7eb88fdb5a)

**Comment by dsizzle** [comment]
@humdingerb I think this ticket can be closed since we have #545 for the Airbrush spray - I didn't think there was any other work for this ticket?

**Comment by humdingerb** [comment]
Indeed!
