### ISSUE TITLE
Global settings: Cursor setting not saved and doesn't work

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#132]
The radio setting between "Tool cursor" and "Cross-hair cursor" doesn't seem to change the mouse pointer appearance. The setting isn't saved either.

I haven't seen the "Cross-hair cursor", I imagine it'll just be the small cross-hair cursor that's also there with the "Tool cursor". IMO, the small additional tool symbol at the mouse pointer never actually distracts or obscures anything important.
I propose to just remove the whole setting.

**Comment by dsizzle** [comment]
I believe in Photoshop, this option allows either a constant cross-hair, no matter the tool, or a different cursor per tool for a quick visual cue of which tool is selected.  I don't mind leaving this option if it can be implemented.

**Comment by humdingerb** [comment]
OK. Adjusting title of the issue.
