### ISSUE TITLE
x86 build: StatusView - SetVisibleItem(int) issue

### ISSUE THREAD

**Issue by kenmays** [HaikuArchives/ArtPaint#138]
Haiku R1B3 x86 - Ref: https://github.com/HaikuArchives/ArtPaint/commit/b86463b388110ed1d240388432733c6ac69e5851

'SetVisibleItem(int)' is ambigous - conflicts with OS Header file  with os/interface/CardLayout.h (i.e. SetVisibleItem(long int))

**Comment by kenmays** [comment]
[artpaint_statusview.txt](https://github.com/HaikuArchives/ArtPaint/files/8544724/artpaint_statusview.txt)

**Comment by dsizzle** [comment]
@korli does it make sense to make the CI build both 32- and 64-bit?
