### ISSUE TITLE
Add ArtPaint to Polyglot

### ISSUE THREAD

**Issue by bitigchi** [HaikuArchives/ArtPaint#143]
Looking forward to this! Thanks in advance.

**Comment by dsizzle** [comment]
I think Polyglot is the right place instead of Pootle. @humdingerb should be able to make this happen.

**Comment by humdingerb** [comment]
Yes, I edited the issue's title.
I wonder if we should wait until the add-ons are translatabled, too. I can have a stab at that, no promises though... :)
Need to figure out first how to collect those catkeys in one file first...

**Comment by bitigchi** [comment]
> I think Polyglot is the right place instead of Pootle. @humdingerb should be able to make this happen.

 I also meant Polyglot, brain fart, sorry!

**Comment by humdingerb** [comment]
Now that the addons are localized as well and @dsizzle found a quick solution to have their translations loaded into the app, ArtPaint is at Polyglot.

**Comment by bitigchi** [comment]
Thanks! Already on it.
