### ISSUE TITLE
Deleting layers during a manipulator operation causes bad behavior

### ISSUE THREAD

**Issue by dsizzle** [HaikuArchives/ArtPaint#144]
In one of the UI changes I moved the Translation and Rotation manipulators out of the Status view and into separate windows like the other manipulators.  However, that means that they can get hidden behind the paint window. 

Since the manipulator dialogs aren't modal, you can do other operations while a manipulator is active - for example, you can merge, re-order, and even delete(!) layers while the Translation manipulator is active. Yikes.  Needless to say it doesn't end well. 

The manipulators should either prevent other things from occurring until they are completed (via Ok or Cancel), or they should be effectively Cancelled if another tool is chosen.

**Comment by dsizzle** [comment]
Actually this is only a problem for delete.  The other Layer operations guard against this by cancelling the manipulator.

**Comment by humdingerb** [comment]
Those manipulation windows could be B_FLOATING_APP_WINDOW_FEEL, to make it less likely to get lost. (At least I think that would make it behave like that...)
The look could also be B_FLOATING_WINDOW_LOOK to have a less prominent title tab.
