### ISSUE TITLE
Airbrush vs Spray

### ISSUE THREAD

**Issue by dsizzle** [HaikuArchives/ArtPaint#148]
Do we need both?  I'm really having a hard time seeing what's different about the two modes.  Can one be removed?

**Comment by PeteCA** [comment]
Yeah, I tried several settings and can't see any difference.  And the manual is
not exactly clear on the effect, either.  I'd be happy with its removal.

**Comment by humdingerb** [comment]
There was a bug that resulted in the use of the airbrush mode, even if spray mode was selected in the tool setup window.
See if you like the fix with #149

**Comment by dsizzle** [comment]
Ah thanks - I should've looked at the code before asking.  Reviewed the fix and it looks good!

**Comment by humdingerb** [comment]
Great, closing ticket.
