### ISSUE TITLE
build.sh: move instead of copy ArtPaint binary

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#153]
Can we move the ArtPaint binary into "dist" instead of copying it?
Having two ArtPaint binaries round terrorizes the "Open with..." menu...

**Comment by dsizzle** [comment]
Probably, but I assume this is only a problem for those of us building ArtPaint from the source. For a user installing via HaikuDepot this wouldn't happen, right?

**Comment by humdingerb** [comment]
Yes, it's just an annoyance for the devs. End-users won't feel a thing.
Doing that then.
