### ISSUE TITLE
Edit menu: Add "Select all" item

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#154]
Add a "Select all" (ALT+A) menu item to the _Edit_ menu down by the other selection related commands.

**Comment by PeteCA** [comment]
Is this much different in practice from 'duplicate layer'?  For all the situations
I can currently think of, I'd think it's safer to generate a new layer.

**Comment by humdingerb** [comment]
You could want to copy the current/all layer/s to a new project or even another application.

**Comment by dsizzle** [comment]
Philosophically, is select-all any different from select-none?  In both cases any operation performed affects the whole layer.

in photoshop, if you select-all and then translate the layer, the select changes to  include only the non-transparent pixels. Should ArtPaint’s select-all just automatically select the non-transparent pixels? 

Or is there another benefit to actually selecting the entire layer frame that I’m not thinking of?

**Comment by humdingerb** [comment]
> Philosophically, is select-all any different from select-none? In both cases any operation performed affects the whole layer.
I think that's correct. Though, having an actual ant-framed selection of the whole layer/canvas is more intuitive. People may not be aware that in this case no-selection is the same as all-selected.

> Should ArtPaint’s select-all just automatically select the non-transparent pixels?
> Or is there another benefit to actually selecting the entire layer frame that I’m not thinking of?

One thing I can think of is if you want to have a one-pixel border around the canvas with a "Stroke selection" - if ArtPaint gains that feature.
What's the benefit of the Photoshop way to only select the non-transparent pixels?

**Comment by dsizzle** [comment]
The benefit of selecting the non transparent pixels is that it’s a super quick way to make a complicated selection. For example if you wanted to stroke some text you could just do the select all and then click stroke selected. Bad example for photoshop because it has other ways to stroke text, but that’s the idea. It’s been awhile since I used photoshop but I remember using that feature frequently.

**Comment by dsizzle** [comment]
I guess photoshop has grown many features and can now do drop shadows as simple layer effects, but that was another use case: select all, go to another layer and paint the select black, then blur it and shift it down and to the right

**Comment by humdingerb** [comment]
I used to do that, too. But I never used "Select All" for that (didn't know it would only select all non-transparent pixels, maybe it was such an old PS version that it didn't back then), I used CTRL+click into the layer window.

I'd say, since you can still select the whole canvas with the Selection tool (once #300 is fixed :) ), go for select all non-transparent.
