### ISSUE TITLE
Edit menu: Add a "Scale..." action

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#156]
ArtPaint misses a way to scale the currently selected part of an image.
Should be similar to the "Scale" window of the _Canvas_ menu, though I think we only need the Width and Height text controls (BSpinner?) and the "Lock" checkbox

**Comment by PeteCA** [comment]
Ohh.. snap! (:-))

I think again, though, I'd always prefer to do it to a layer, rather than a selection.

**Comment by humdingerb** [comment]
I think it's easy to do a quick ALT+A to select the whole layer and do the resizing.  OTOH, if you could only scale the whole layer, you'd need to first copy a selection, paste it to a new layer and then do the resizing and possibly afterwards merge the layer back to the layer below.

Maybe a good compromise: If there's nothing selected, scale the whole layer.

In any case, currently there's only scaling for the whole canvas, i.e. you couldn't even scale just one layer.

**Comment by PeteCA** [comment]
> Maybe a good compromise: If there's nothing selected, scale the whole layer.
> 
Actually, this makes a lot of sense.  For the resize/rotate/etc operations we're
talking about, you're not likely to want to apply them to an empty selection(!),
so having  the default be  the whole layer seems sane.

**Comment by dsizzle** [comment]
ugh, this is not trivial.  I spent the last several days on this.  will revisit again later.
