### ISSUE TITLE
Global settings: "Keep in front" options act weird

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#158]
* Make sure the default "Keep in front" setting is all 'off'.
* Show all the windows from the "Windows" menu.
-> Now the canvas window obscures all those windows
* Turn all "Keep in front" settings "on".
-> Now the canvas window is behind all those windows
* Restart ArtPaint.
-> Now the Brushes, Layers and Toolsetup windows are non-floating again, so the canvas window obscures them. Only the Color palette and Tool selection windows are immune.

If you enter the Global settings again, the checkmarks are all still "on". Click "Apply" and all the windows have the correct floating feel again.

If you close e.g. the Brushes window while floating and re-open it, it's again a normal non-floating window.

Weird.

**Comment by dsizzle** [comment]
probably just not properly loaded from settings when the windows are created, if I had to guess.
