### ISSUE TITLE
Wave add-on crashing ArtPaint when quitting with not saving changes

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#165]
* Open ArtPaint
* Create a canvas
* Draw something
* Quit and "Don't save changes"

-> Bam!  Debug report:
[ArtPaint-debug.report.txt](https://github.com/HaikuArchives/ArtPaint/files/8646545/ArtPaint-debug.report.txt)

When started with: `LD_PRELOAD=libroot_debug.so dist/ArtPaint ` it crashes right away with this report:
[ArtPaint-ld_preload-debug.report.txt](https://github.com/HaikuArchives/ArtPaint/files/8646549/ArtPaint-ld_preload-debug.report.txt)

Everything's built with DEBUG=TRUE. The Debugger hints at the issue being with config_view->RemoveSelf(); of
https://github.com/HaikuArchives/ArtPaint/blob/master/addons/AddOns/Wave/Wave.cpp#L76

@dsizzle , any ideas?

**Comment by dsizzle** [comment]
Added PR #166  - the issue is that config_view wasn't initialized to NULL in the constructor, so there's a chance it is holding garbage data when the add-on is destroyed at shutdown.  So the "if config_view != NULL" check unfortunately succeeds when the view hasn't actually been instantiated.

**Comment by humdingerb** [comment]
Thanks for the quick fix!
I suspected as much and tried the same fix, but I may have checked on an older no-debug(?) binary I had hanging around and seeing the same crash, I thought I overlooked something... :)

**Comment by dsizzle** [comment]
well, I didn't spend a ton of time on it - I just know the uninitialized value *is* a problem that causes this kind of crash.  Whether or not there's something else wrong i didn't dig.

**Comment by humdingerb** [comment]
Nah, it's OK. I think it was just me accidentally testing an older binary...
