### ISSUE TITLE
Brush tool enhancements v2

### ISSUE THREAD

**Issue by dsizzle** [HaikuArchives/ArtPaint#169]
After consideration:

- convert width and height sliders to 'size' and 'ratio' instead.  This allows a user to simply resize a brush without messing with the proportions
- Fade slider doesn't work well. With a smaller brush, the fade quickly overtakes the brush and makes it transparent.  It should work like a percentage and make the edges soften towards the center. At 100% there should always be at least 1 pixel of the original color, like this:
![brush-rect](https://user-images.githubusercontent.com/10878750/168410055-3add64ca-600c-40bc-9b41-efc626374a00.png)

**Comment by humdingerb** [comment]
:+1: 
Just for reference, this was discussed a bit at 7c210ff4eb004d3af12aee301f557417b6f5ed9d.

While you're at it, maybe naming it "Hardness" (think "pencil") would be better than "Fade". "Fade" could be taken like the "Color amount" of the hairy brush tool, i.e. the alpha fades over time while you paint.

**Comment by dsizzle** [comment]
yes, Hardness is a better term.  Totally agree.

**Comment by PeteCA** [comment]
On Sat, May 14, 2022 at 07:53:18PM -0700, Dale Cieslak wrote:
> yes, Hardness is a better term.  Totally agree.
> 
might as well chip in with a "Me too"... (:-))

**Comment by dsizzle** [comment]
Actually with the direction of the slider it should be "Softness" - if "hardness" makes more sense the function of the slider needs to be flipped.

**Comment by humdingerb** [comment]
Yeah, I noticed that too when I translated to German.
I think "Hardness" is used more commonly, so flipping the slider would be good.
