### ISSUE TITLE
Replace Transparency tool with options for Eraser

### ISSUE THREAD

**Issue by dsizzle** [HaikuArchives/ArtPaint#176]
The Transparency tool is hard to understand.  The Eraser tool would be more intuitive with some options:

- "Pressure" or "Strength" or something to say how transparent to erase
- "Hardness" like the Brush tool for soft edge erasing

**Comment by humdingerb** [comment]
After looking at the transparency tool for the user docs, I'm not so sure anymore it should be integrated with the eraser. While the eraser could do the "make-slightly-transparent" part with the above mentioned "Pressure/Strength", it cannot do the reverse: make something less transparent. A sort of "anti-eraser"...

I'm coming around to how the transparency tool is working... :)
From the user doc:

> This tool changes the transparency of the touched pixels by applying the "alpha" value of the current foreground color.
> 
> Say you have one image in layer 1 and another in layer 2 above it. If you set the transparency (=alpha) of the foreground color to 50% (the actual color doesn't matter), and start painting in layer 2, the touched pixels become max. 50% transparent and the image of layer 1 shines through.
> 
> If you then set a color with alpha 100%, i.e. fully opaque, you can restore the original image when painting over the same areas you reduced the alpha values before.
> 
> You can set the "Size" of your transparency brush.
> "Speed" controls how fast the alpha value is applied: the lower the speed, the longer it takes for the pixels to become transparent/opaque.

However, it may be more obvious to forget about the alpha of the current foreground colour and just add another slider "Transparency" from 0% to 100%...

**Comment by PeteCA** [comment]
On Tue, Jun 07, 2022 at 09:05:50AM -0700, humdinger wrote:
> After looking at the transparency tool for the user docs, I'm not so sure anymore it should be integrated with the eraser.

I think combining the two tools would *not* be a good idea.  Your analysis
explains why!

**Comment by dsizzle** [comment]
I still think it’s a weird, unintuitive tool and this use case would be better served via a mask. Basing the transparency on the opacity of the currently selected foreground color is imprecise and confusing - especially given the way the “speed” part works.

I agree that ditching the Transparency tool sounds like we’d be losing functionality so that’s not a good idea.

Having said that, I think if we add functionality to Eraser, and make Transparency more intuitive, the tools will be quite close. Maybe Eraser needs an “unerase” mode as @humdingerb suggests?

**Comment by humdingerb** [comment]
> Basing the transparency on the opacity of the currently selected foreground color is imprecise and confusing - especially given the way the “speed” part works.

Yes, I think going with a "Max. transparency" slider going from "opaque" to "transparent" would be better than using the foreground colour.
The "Speed" is working much as the "Flow" parameter of the airbrush tool. Maybe we should re-use the term.

I was never much of a mask-user, though I'm of course only a graphics dabbler... Also, masks would need some work on ArtPaint's layers and blending first.
Anyway, I'd appreciate having a tool to in/decrease alpha in a painting sort of way.

If anything, the Eraser tool becomes redundant with the more powerful Transparency tool. :)

[BTW, the Transparency tool reminds me of a Simpson's episode, where Homer plans to become morbidly obese to be able to work from home. He only eats fatty things and to find out if something is oily enough, he rubs it on a wall and sees if it becomes transparent, like sandwichpaper... :D ]

**Comment by dsizzle** [comment]
> The "Speed" is working much as the "Flow" parameter of the airbrush tool. Maybe we should re-use the term

Yes, but under the hood it's just addition/subtraction. I.e. if your "Speed" is 100 and the difference in alpha between the layer and the selected color is 255, it takes 3 clicks to go fully to the alpha. But if the difference is 100 or less it takes 1 click. And not knowing that difference means its hard to control. I'd rather change it to percentage so you know exactly how many clicks to get there...100% "speed" would be 1 click to get to the target alpha, always.

> masks would need some work on ArtPaint's layers and blending first

Yes. It's in the "future direction". But masks are super powerful. If you see someone doing heavy photo editing there are masks everywhere. 

> If anything, the Eraser tool becomes redundant with the more powerful Transparency tool. :)

I think we will always want a way to remove pixels completely vs. just making them invisible.

**Comment by PeteCA** [comment]
On Wed, Jun 08, 2022 at 10:12:17AM -0700, Dale Cieslak wrote:
> 
> > masks would need some work on ArtPaint's layers and blending first
> 
> Yes. It's in the "future direction". But masks are super powerful. If you see someone doing heavy photo editing there are masks everywhere. 

Agreed.  I've used them a lot whenever I get to use The Gimp.
> 
> > If anything, the Eraser tool becomes redundant with the more powerful Transparency tool. :)
> 
> I think we will always want a way to remove pixels completely vs. just making them invisible.
Again, agreed.

**Comment by humdingerb** [comment]
OK. See if I summarize correctly.

* Keep the eraser tool as is, i.e. completely remove pixels and replace with colour/transparency.
* Remove the "alpha-of-foreground-colour-decides-on-mode" thing of the Transparency tool.
* Add a "Transparency" slider to go from "Opaque" to "Transparent" (or 0% to 100% ?)
* Remove the "Speed" slider, just set the transparency with the new slider and get the effect with the first click.

**Comment by dsizzle** [comment]
Half agree. 😄 

> Keep the eraser tool as is, i.e. completely remove pixels and replace with colour/transparency.

I still l think eraser would benefit from opacity and soft edges.

> Remove the "alpha-of-foreground-colour-decides-on-mode" thing of the Transparency tool.

Yes.

> Add a "Transparency" slider to go from "Opaque" to "Transparent" (or 0% to 100% ?)

Yes.

> Remove the "Speed" slider, just set the transparency with the new slider and get the effect with the first click.

no, I think “speed” needs to be a % instead of a value, and rename to “pressure” or “strength” (whichever matches other tools).

**Comment by humdingerb** [comment]
Alright then, you've cut your work out for yourself. :)
Shall I close this ticket and open new ones for the above, i.e.:
* Eraser: Add slider for "Pressure" (for opacity) and "Hardness" (for soft edges).
* Transparency: Add slider "Max. transparency" (0% to 100%)
* Transparency: Rename slider "Speed" to "Pressure" and make it a percentage of when "max. transparency" is reached.
