### ISSUE TITLE
Tools: Use stored brushes for more tools

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#177]
Since we can configure brushes and store them for later use, it'd be nice to re-use those brushes for other tools.
Candidates are: ~~freehand-line and straight-line, rectangle and ellipse (if they are outlines, not filled)~~, blur, eraser

A checkbox at the top, "Use current brush" with a tool tip "Stored in the Brushes window". When set, related sliders Size or Width need to be disabled.

To always work, we have to make sure a default brush is always available in the Brushes window. That'd be similar to color sets.

The main work is probably to have those tools actually use those stored brushes...

**Comment by dsizzle** [comment]
As mentioned before, freehand line is equivalent to a brush stroke already. Making it use the brushes would be even more redundant. I vote to just eliminate freehand line.

For straight line, it might make more sense to add a modifier or mode to brush to draw straight lines.

**Comment by PeteCA** [comment]
On Thu, Jun 02, 2022 at 12:26:47AM -0700, humdinger wrote:
> +1 on eliminating the freehand tool.
> 
> Moving straight lines into the brush tool, I'm not so sure about.
I think I agree with the above.  Straight lines are something one does a lot.
Probably justifies a separate tool.
> 
> Though one day, it would be nice to be able to draw with any shape (from a selected part of the image or predefined stencils etc.) and then using those brushes with different tools may be nice...

I've often missed the feature in Amiga's old Deluxepaint, where a brush could
be any image.  If you painted with it, it would essentially stamp multiple copies
along the path, depending on how fast you moved, but the effect could be
quite impressive.

**Comment by humdingerb** [comment]
> I've often missed the feature in Amiga's old Deluxepaint[...]

I think I remember that, too. It's been a long time... :)

**Comment by dsizzle** [comment]
Lol, I used DP III or IV on DOS (I never had an Amiga) back in the 90s. Great program.

I think Photoshop also lets you make a selection into a brush. The brushes in ArtPaint are just monochrome with alpha right now, but it could either be extended to use colored brushes, or a separate "stamp" kind of tool.

**Comment by humdingerb** [comment]
> it could either be extended to use colored brushes, or a separate "stamp" kind of tool.

Yes, I use the stamp tool all the time (in Photoshop at work) to copy one part of an image a bit further down in the image. As I move the mouse, the source follows my mouse pointer. Harder to put into words than expected... :)

Anyway, this got me thinking about what direction you want to go with ArtPaint.
Please comment at #194.

**Comment by dsizzle** [comment]
Can thsi be closed?  Anything else that could use stored brushes?

**Comment by humdingerb** [comment]
At least with the current state of the tools. The rectangle and ellipse tools could use a brush as stroke.

However, maybe having a more general "Stroke selection" (and "Fill selection" for that matter) could offer to "Use current brush".
Closing this then and open specific issues when they crop up..
