### ISSUE TITLE
Selection tool: Lock aspect to 1:1 with CTRL

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#179]
Just like the Rectangle and Ellipses tools, the Selection tool should lock the aspect ratio to 1:1 when you hold CTRL while creating the selection to result in a square selection (and a circle, once #118 is implemented).

**Comment by humdingerb** [comment]
Duplicate of #318

**Comment by dsizzle** [comment]
this can be closed.

**Comment by humdingerb** [comment]
Yep. Aspect locks with SHIFT.
