### ISSUE TITLE
Fill tool: Gradient drawing is awkward

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#182]
I'd expect that the first click into the canvas sets the left hand colour from the setup window, the second click will set the right hand colour. Between those points is the gradient.

Currently it seems the first click sets the right hand colour, and the second click - depending how far away from the first click - sets the right hand colour again, and some point after the second click is a compressed gradient towards the left-hand colour.
Weird. I say this is a bug, because no twisted mind could have come up with that... :)

Also, a connecting line from the startpoint when the mouse is moving to find the endpoint would be nice.

**Comment by dsizzle** [comment]
I also don’t think the gradient handles alpha properly. I tried to do a solid color on one end and pure transparent on the other, and the pure transparent end came out black.

**Comment by humdingerb** [comment]
Total opposite here. :) Solid blue at the left end, total transparent to the right. As described in this ticket - when clicking on the left side, move mouse to the right and let go - the blue appears at the right. What should be transparent is white, not black as it's for you... weird.

**Comment by humdingerb** [comment]
All done! \o/
