### ISSUE TITLE
Crash if selection is changed during a manipulator

### ISSUE THREAD

**Issue by dsizzle** [HaikuArchives/ArtPaint#186]
Not surprising; steps to reproduce:

1. Make a selection
2. Press Alt+R to go into rotation manipulator
3. Rotate selection (but don't press Ok)
4. Press Alt+D to clear selection
5. Press Alt+Z to undo

:boom:

**Comment by humdingerb** [comment]
Fixed!
I have another crash, I'll file a ticket for in a moment. :)
