### ISSUE TITLE
Text only draws in black

### ISSUE THREAD

**Issue by dsizzle** [HaikuArchives/ArtPaint#197]
Text tool should respect the current colors, but instead it only renders black.

**Comment by PeteCA** [comment]
On Sat, Jun 04, 2022 at 08:27:08PM -0700, Dale Cieslak wrote:
> Text tool should respect the current colors, but instead it only renders black.
> 
Unless things haver changed recently, this isn't exactly so.  However, I've just
spent about half an hour (with the old version) getting totally confused.
Then I finally went to the (old!) manual, and everything became clear!
It is definitely not 'intuitive'...
Basically -- in brief -- you need to have *both* the text-entry window *and*
the color window open.  Then any *change* in the color window will be
reflected in the text.  Not quite 'live' -- you have to release the mouse button
before it shows.  That color is retained for text only, unaffected by any later
color changes in foreground or background color.

As an example sequence:
	Select the text tool, and click on the canvas to make it active.
	Also open the color selection window.
	Make a desired *change* to the color window.
	The text should change to the selected color.
	If any characters of the entered text are selected, only they
	will change color.  Any insertions seem to assume the color
	of the surrounding characters, but only the last color selection
	is retained.

Hope that makes sense. I suspect it was a deliberate choice, so text color
is essentially independent of others, but it is definitely confusing to a naive
user!  I suspect we can do better, but I have no good ideas ATM.

**Comment by humdingerb** [comment]
Excellent work, Pete Holmes! :)

But yeah, a bit weird. It doesn't make much sense having the colour apply to the slected part of the text, if font and size always apply to the whole text. (Rotation and shear won't make much sense if applied to parts of the text, I think).

I suggest, for now, to either
a) always make the whole text the foreground colour, and start with a foreground coloured text.
b) also optionally apply font and size to just a selection of text and apply a changing foreground colour live.

Maybe there should be a colour well added that shows the current foreground colour and openes the Colors window when clicked. That's suggest to change the colour in the Colors window, if you want the text colour changed.

**Comment by dsizzle** [comment]
Yes, thanks for the investigation, Pete!!

While it does sound flexible and potentially interesting, it also sounds completely awful from an intuitivity(?) and discoverability perspective.  

I've always liked the "Principle of Least Surprise" when it comes to UI/UX so I think it should always use the current foreground color. It makes sense and is consistent with every other tool. 

I didn't list anything in the "future of ArtPaint" ticket but there's certainly a lot the can be done with text. In photoshop text stays as vectors until you explicitly rasterize it, which gives you a ton of flexibility.  ArtPaint rasterizes as soon as you're done. I'd guess WB lets you do a lot of fun stuff with text in vector form.

**Comment by humdingerb** [comment]
Wonderbrush's (v2, the next version v3 is being stuck in dev for approaching a decade sadly) text tool is also quite basic when it comes to styling. The whole text is one colour and one font. But it is editable and has alignment and spacing, inset, kerning, hinting and more.

**Comment by humdingerb** [comment]
> I'd guess WB lets you do a lot of fun stuff with text in vector form.
Just wanted to add, of course when you're done with the text-editing, you can also convert the text to vector shapes which you can then manipulate by moving bezier points around etc. So, fun is to be had.

**Comment by PeteCA** [comment]
Addendum:
Any text left in the text area when you hit OK will retain its color when 
the text window is reopened. Any appended text will have the same color.

If you clear the text before hitting OK, future text will be black!  If you
*prepend* to existing text it will probably be black too.
