### ISSUE TITLE
Show current brush in main window and use if for all suitable tools

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#202]
Thinking more about #177.

What about this: Similar to the current colour, ArtPaint shows the current brush. 
Mockup:

![show-current-brush](https://user-images.githubusercontent.com/6107158/172363882-4b23be16-14e7-47f2-9086-f6e35ada1460.png)

This brush (ellipse|rectangle/size/aspect/angle/hardness) will be used for suitable tools: brush, blur, transparency, eraser (and in future other tools like lighten/darken, smudge, stencil, whathaveyou).
This will remove having that configuration (ellipse|rectangle/size/aspect/angle/hardness) for all tools,  which currently only have a Size slider and could do with different brushes. (BTW, is there a better word for "Brushes"? Once it's used for different tools, something more generic would be nice. "Tool tips", "Tool tops"?)

A left-click opens what's currently the Brush tool setup.
A right-click opens the Brushes window with stored settings.

**Comment by PeteCA** [comment]
On Tue, Jun 07, 2022 at 04:11:09AM -0700, humdinger wrote:
> Thinking more about #177.
> 
> What about this: Similar to the current colour, ArtPaint shows the current brush. 
> Mockup:
> 
> ![show-current-brush](https://user-images.githubusercontent.com/6107158/172363882-4b23be16-14e7-47f2-9086-f6e35ada1460.png)
> 
This might have trouble with larger brushes, unless the bar area expands
appropriately?

I think "brush" is probably the best term we have.  It's "intuitive', anyway...

**Comment by PeteCA** [comment]
On Tue, Jun 07, 2022 at 12:32:32PM -0700, humdinger wrote:
> It'll always be this same size, just like it's now in the brush tool setup. There's a small red line at the bottom of the brush shape (which I forgot on the mockup) that gives a scale.
> 
Heh!  All this time using ArtPaint and I never noticed that!

**Comment by humdingerb** [comment]
> Photoshop puts a small number on the brush to indicate the size, like a 400px brush would say “400” on it.

That could be a nice addition. I think tool tips that show size, aspect, angle, hardness may be too disruptive. If those details are of interest, people can open the brush setup window.

> Overall I’d like to think on this more. Intuitively it’s not a bad idea but it might be a massive code refactor.

Probably. :)

**Comment by dsizzle** [comment]
Ok, I need opinions/feedback here.  I have separated the Brush from the Brush Tool so that it is available globally for any tool, but now I have questions @humdingerb @PeteCA (or anyone else with opinions):

1. should the Brush Editor be combined with the Stored Brush window?  Or should it be a new separate window?  It doesn't make sense to be in the Brush Tool settings anymore if it's going to pop up when you click on the Brush in the Status View.  I believe in Photoshop the two are combined. 
2. What Brush settings should a user be able to edit in any given tool? I was thinking maybe only Size and Hardness?  Or only Size?  or neither, since you can adjust it by opening the Brush Editor at any moment regardless of the active tool?

**Comment by humdingerb** [comment]
> 1. Should the Brush Editor be combined with the Stored Brush window?

Maybe it should be in one window with a "Setup" tab and a "Stored brushes" tab. The original suggestion:

> A left-click opens what's currently the Brush tool setup.
> A right-click opens the Brushes window with stored settings.

would still work, opening the according tab.
I wonder though, if you'd ever wanted to view the stored brushes while twiddling the brush setup... You may find that you want to see what brushes you already got and specifically create a new one "in the middle" of two existing ones (wrt size or hardness).
Having both Setup and Stored brushes in one window with no tabs, would result in quite a large window, however...
Maybe just two visible rows of stored brushes (should fit ca. 12 brushes) below the brush setup (optionally with a vertical scrollbar).
Plus "Brush sets" like we already have with "Color sets" and  < / > buttons to switch between sets. Having smaller sets of related brushes seems like a good idea anyway.

If we do go with one window setup/stored brushes, that'd mean we could have two brushes put in the status bar and switch between them with a right-click. Analog to how the colour swatches work.

> 2. What Brush settings should a user be able to edit in any given tool?

How about keeping the tools' current width/size slider and add another checkmark "Use current brush".
I kinda like especially the straight line tool's "Adjustable width" when I just want to draw some lines and don't want to configure a brush or search for a stored brush. It's so nicely interactive, when I otherwise have to try out-undo-try out-undo-try out until I find the right brush size...
"Adjustble width" would also be nice for rectangle and ellipse tools (there's a ticket for that I think).
A checkmark to "Use current brush" would override the tool's width/size setting.

BTW, outsourcing the brush setup means we can retire the Brush tool and only have Freehand instead, right?

**Comment by dsizzle** [comment]
> Maybe just two visible rows of stored brushes (should fit ca. 12 brushes) below the brush setup (optionally with a vertical scrollbar).

Yeah, I think with just a few rows it'd be fine.

> Plus "Brush sets" like we already have with "Color sets" and < / > buttons to switch between sets. Having smaller sets of related brushes seems like a good idea anyway.

Yes, this would be nice, but it should be a separate ticket imo.

> If we do go with one window setup/stored brushes, that'd mean we could have two brushes put in the status bar and switch between them with a right-click. Analog to how the colour swatches work.

I'm not sure how I feel about this. It should also be a separate ticket.

> How about keeping the tools' current width/size slider and add another checkmark "Use current brush".

Ok. I had thought of this same idea. I think it makes sense.

> "Adjustble width" would also be nice for rectangle and ellipse tools (there's a ticket for that I think).
A checkmark to "Use current brush" would override the tool's width/size setting.

Using the current brush for rectangles and ellipses was not in my current plan - that's definitely not in v1 of this ticket.

> BTW, outsourcing the brush setup means we can retire the Brush tool and only have Freehand instead, right?

Yes, or vice versa.  We could get rid of Freehand and only keep Brush (I thought that's what we'd discussed in the past).

**Comment by humdingerb** [comment]
> Yes, this would be nice, but it should be a separate ticket imo.

I just wrote down some ideas why thinking about the issue. First things first, let us wait with potential enhancements and get the fundamentals first. And when I say "us", I mean "you" of course...

> Using the current brush for rectangles and ellipses was not in my current plan - that's definitely not in v1 of this ticket.

Yeah, I thought more of the "adjustable width" and got carried away...
It may even be better to not do the use-brush-to-stroke-rect/ellipses at all and go a more general route: Add a "Stroke selection" and offer to use the current brush as an option. After all, you can create a rect/ellipse selection. I know, again, separate ticket. :)

> Yes, or vice versa. We could get rid of Freehand and only keep Brush (I thought that's what we'd discussed in the past).

Also possible. Though, getting rid of "Brush" would be nice to make the "Hairy brush" 'more' unique. Also, in my mind the brush tool is more like a pen anyway.

**Comment by dsizzle** [comment]
opinions - horizontal (minimal color palette for scale):
![brush-ed01](https://user-images.githubusercontent.com/10878750/229413599-4e64d3ba-d441-4bc9-b884-d067bb92f3e8.png)

vertical:
![brushedit02](https://user-images.githubusercontent.com/10878750/229413655-ac797750-9285-448f-b711-c4f471632dfa.png)

My personal opinion is that the vertical version wastes less space in both the minimal and maximal configuration.

**Comment by dsizzle** [comment]
Can this be closed?  I don't think there are any other tools that could use the current brush.
