### ISSUE TITLE
Show correct version in the About window

### ISSUE THREAD

**Issue by Begasus** [HaikuArchives/ArtPaint#220]
New `2.3.0 release` shows `Version 2.3` in the about window.

**Comment by Begasus** [comment]
Well, maybe BAboutWindow should get an update to show MAJOR MIDDLE MINOR?

**Comment by humdingerb** [comment]
I suspect that this is on purpose. Many projects use just MAJOR MIDDLE for their versioning. Their MINOR version is always "0" and can be left from the AboutWindow.
