### ISSUE TITLE
Text tool typing box can be unreadable

### ISSUE THREAD

**Issue by Briseur** [HaikuArchives/ArtPaint#229]
The typing box uses document background colour but the text is in black so this is causing problems with dark colour schemes.
I see two solutions:
The first would be to use document background colour and document text colour there.
The second would be to use a fixed white colour background. Indeed, since (from what I understand from issue 197) ArtPaint only draws text in black, it makes sense to have the text in black in the typing box.
 
![Artpaint text tool](https://user-images.githubusercontent.com/37412120/184503802-de43e789-da26-4bc6-abb0-e39c470e2dc7.png)

**Comment by humdingerb** [comment]
> * The first would be to use document background colour and document text colour there.
> * The second would be to use a fixed white colour background. Indeed, since (from what I understand from issue 197) ArtPaint only draws text in black, it makes sense to have the text in black in the typing box.

ArtPaint does not only draw text in black. If you have the Colors window open and select some letters of your text, their colour will change with changes in the Colors window.

Your first solution may be OK for now: Always use system colour constants for text and background and only do the WYSIWYG (colour, size, font etc.) live on the canvas.

Ideally, the text handling will be changed some day to do away with the "Enter-text-box" and you enter the text directly on the canvas in a special text layer, where the text and its properties can always be edited until it's rastered to bitmap.
