### ISSUE TITLE
Transparency tab of preferences has a weird layout

### ISSUE THREAD

**Issue by Briseur** [HaikuArchives/ArtPaint#230]
![ArtPaint-prefs-trans](https://user-images.githubusercontent.com/37412120/184504266-50b9f1b8-ae30-4122-b1d6-2d8f351d0997.png)

**Comment by dsizzle** [comment]
Thanks for reporting!  

This is a general problem with the Settings window.  I see the same issue with the "Windows" tab:
![00fenetres](https://user-images.githubusercontent.com/10878750/185848729-efc66074-0dff-4a3e-b9e0-7b9fa167b119.png)

**Comment by Briseur** [comment]
Oops! Indeed, I missed this one.
Thanks for your interest in fixing Artpaint. It seems a never ending task but it already works way better.
