### ISSUE TITLE
Colors window not font-sensitive

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#231]
Setting a large font size releveals the issue:

![colors](https://user-images.githubusercontent.com/6107158/185546287-e9220043-7e90-4ee7-8403-e98e41dd7828.png)

* colour squares in the palette view need to resize
* arrow widget to switch colour sets need to resize
* spacing of colour sliders need to adjust

[Mentioning #45, to add this issue to the meta ticket.]

**Comment by dsizzle** [comment]
thanks!  I *think* this and the Save dialog might be the last 2 layout API holdouts?

**Comment by humdingerb** [comment]
Yes. The above also applies to the main window's colour widgets.
Some of the save dialog issues seem to be a Haiku issue. Other save panels (e.g. StyleEdit's) show cut off Cancel and Save buttons, too.

**Comment by dsizzle** [comment]
thinking of removing YIQ - I am not convinced anyone actually selects color in that space.  Maybe as a color space conversion but not as a color selection mode?

on the other hand I will likely add a few more that seem common - LAB? HSL? XYZ?

**Comment by humdingerb** [comment]
I'm just a amateur dabbler who doesn't even print things out, so my demands are very low.
When in doubt, I'd suggest once more to look to Photoshop. They normally know what people really need, which isn't always the case for the open source alternatives...
