### ISSUE TITLE
32bit: Tall text fields in 'Create canvas' panel

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#241]
Only on 32bit builds:

![new-canvas](https://user-images.githubusercontent.com/6107158/186155498-e6da9101-3bb2-4dbe-9f1c-9eaa3b20b39b.png)

The text fields should be just as high as one line of numbers, like in 64bit builds.

**Comment by dsizzle** [comment]
I'm not even sure how that would be different between architectures?

**Comment by humdingerb** [comment]
Search me... :)

**Comment by humdingerb** [comment]
Solved.
I tested on a 32bit beta3 Haiku installation. Not a bad idea, generally, when testing for build failures before an ArtPaint release. I now tested with a current 32bit nightly image, and this issue is gone. Even if we release another ArtPaint before a Haiku Beta4, this slight glitch doesn't matter.
