### ISSUE TITLE
Closing Tool window and then re-opening it crashes ArtPaint?

### ISSUE THREAD

**Issue by dsizzle** [HaikuArchives/ArtPaint#245]
I tried with 2.3.0 and it happens there too - steps to reproduce:

1. Close Tool window
2. Re-open Tool window via Windows->Tools 

restarting ArtPaint works fine, but this is crashing 100% for me.  Is it just me?  trying to debug...

**Comment by humdingerb** [comment]
Here too.

This is the output with heap protection, if that helps at all:
```
/Source/ArtPaint> LD_PRELOAD=libroot_debug.so MALLOC_DEBUG=grs25 dist/ArtPaint
flags: used first dead
allocation size: 392
allocation base: 0x10d4c12fe70
alignment: 16
allocating thread: 10871
freeing thread: 10876
alloc stack trace (8):
        <libroot.so> _Znwm + 0x20
        <_APP_> _ZN19ToolSelectionWindow8_AddToolEPK11DrawingTool + 0x8d
        <_APP_> _ZN19ToolSelectionWindowC1E5BRect + 0x13b
        <_APP_> _ZN19ToolSelectionWindow10showWindowEv + 0x149
        <libbe.so> _ZN7BWindow11task_looperEv + 0x1d1
        <libbe.so> _ZN7BLooper7_task0_EPv + 0x23
        <libroot.so> _thread_do_exit_work + 0x89 (nearest)
        0x7feea1bc1258 (lookup failed: Invalid Argument)
free stack trace (13):
        <libroot.so> _Z5panicPKcz + 0x3d4a (nearest)
        <libbe.so> _ZN5BViewD2Ev + 0x78
        <_APP_> _ZN10MatrixViewD0Ev + 0x20
        <libbe.so> _ZN5BViewD2Ev + 0x78
        <libbe.so> _ZN5BViewD0Ev + 0x12
        <libbe.so> _ZN7BWindowD1Ev + 0xb9
        <_APP_> _ZN19ToolSelectionWindowD0Ev + 0x12
        <libbe.so> _ZN7BLooper4QuitEv + 0x182
        <libbe.so> _ZN7BLooper14_QuitRequestedEP8BMessage + 0x39
        <libbe.so> _ZN7BWindow11task_looperEv + 0x1d1
        <libbe.so> _ZN7BLooper7_task0_EPv + 0x23
        <libroot.so> _thread_do_exit_work + 0x89 (nearest)
        0x7feea1bc1258 (lookup failed: Invalid Argument)
Kill Thread
```

**Comment by dsizzle** [comment]
I plan to try to bisect it to see when it broke. I only ever remember one change to the tool window which was super minor- it couldn’t have been like this the whole time, right??

**Comment by humdingerb** [comment]
Sure it can. Who closes the Tools window...?  :)

**Comment by humdingerb** [comment]
The crash only happens when the window has no canvas yet, i.e. the "Create canvas" window shows. Even when you open an additional "New project...", the crash only appears if you invoke the "Windows  | Tools" from the new emtpy window. Not crashing when summoning the Tools window from the first, canvassy window.

**Comment by dsizzle** [comment]
Ok, this crash appears as far back as when I first started ArtPaint, so I am convinced I didn't break it. :laughing:

**Comment by dsizzle** [comment]
Also I still get crashes if I create a new canvas and then close/reopen the tools window

**Comment by PeteCA** [comment]
On Thu, Aug 25, 2022 at 09:15:46PM -0700, Dale Cieslak wrote:
> Ok, this crash appears as far back as when I first started ArtPaint, so I am convinced I didn't break it. :laughing: 
> 
Heh, heh!  Yeah, I just tried it with the last version of ArtPaint that I worked
on (2.1.2 Oct 1917), and I can make it happen there!  Not every time -- sometimes 
I needed to create a second instance with no canvas yet -- but fairly reliably.

So it ain't your fault! (:-))

**Comment by PeteCA** [comment]
Dunhh...:grinning: I was a century out, of course: "Oct 2017"!

**Comment by dsizzle** [comment]
haha, wow, I'm impressed with the amount of coding experience you have! :rofl: 

I kinda wish this *was* my fault because then I might have an idea how to fix it...I can get the window to not crash but then the selection is wacky, and then sometimes it eventually crashes.  Seems like maybe a race condition with the tools manager?
