### ISSUE TITLE
Don't update Colors panel live when using colour picker tool

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#253]
When using the colour picker tool, the Colors window gets updated live, the fg/bg colour wells of the main window does not. IMO, since the colour picker tool already has a live preview, the Colors window should also only get updated on mouse-up.

**Comment by dsizzle** [comment]
Ironically the Colors window doesn't update if you just single-click the color picker in the image...but the main window color well does.
