### ISSUE TITLE
Label color sets

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#255]
It may be nice to have an indication what color set is currently shown in the Colors window.
How about a label "Set 1" etc. to the right of the arrow widgets that switch sets below the palette?
~~Or as a text control to have the user name their color set, if that's not too much hassle.~~

Edited: Since the arrow widgets have moved to the right of the palette, there's less space now, so maybe just the number, no "Set", no user edited labelling.

**Comment by dsizzle** [comment]
it might be nice to find room to put a label. I can certainly see a use for wanting to name palettes, but agree that a number might be helpful too?

**Comment by humdingerb** [comment]
Yeah, the set number should do. Not enough space for a proper label and a number helps to navigate the normally few number of sets.

**Comment by dsizzle** [comment]
What do you think about a label underneath the color set, like this?  

![0palette](https://user-images.githubusercontent.com/10878750/211980232-d76db338-e23d-4fa4-a4d1-124d283c37da.png)

**Comment by dsizzle** [comment]
also - what do you think about putting the color set in a different tab or something?  I think the palette should be allowed to be larger than 64.  As it is, the 64-color sets have pretty small swatches. If it was in a different tab we could support larger color sets with larger swatches. And, the overall window could be smaller.

**Comment by humdingerb** [comment]
Tabs are OK, but have the disdvantage that you can only set/manipulate one thing at a time: either the palette or the sliders.
How about this - very rough - mockup:

![colours](https://user-images.githubusercontent.com/6107158/211997273-eedeadc9-a9e7-42ed-9b19-2ae8897602ea.png)

The slider part above is fixed, resizing the window vertically will only resize the palette below. That way you can make the window small if you have few palettes or don't need big swatches. The zoom-widget of the window could do intelligent vertical resizing to switch between adequately large swatches for the current number of colours, and the user-set size.

**Comment by dsizzle** [comment]
My first impression is not favorable, perhaps because it seems so large. What if the color set was a completely separate window? That way it could be Stacked/Tiled depending on the user’s preference? And if you don’t use color sets you could even keep it closed.

**Comment by humdingerb** [comment]
Well, it's only so large because I mocked the window to be very tall. If you had only 16 colours and made it a bit smaller, it'd be:

![colors_shorter](https://user-images.githubusercontent.com/6107158/212259825-cf727a54-9761-49c9-9e90-3983b4408e87.png)

Maybe the whole palette view could be collapsible with some widget similar  to Deskbar's expanding app  windows feaature.

A dockable separate window would also be cool. In fact, all windows  being stack&tilable would be nice.
I'm not sure though, if Haiku's API for that is up to scratch. We'd want to have the window configuration remembered. If you show some window, automatically S&T it to the remembered position.
Also, while side-by-side tiling is working OK, when doing it vertically the window tabs kinda get in the way. Haiku supports window tabs on the side instead of them being on the top. So it would be nice to slide them to the side when tiling vertically. (Hmmm... I may have confused that with tabview tabs... which would put a damper on the tiling idea...)
I'm not sure the API to control this is all in place yet.
