### ISSUE TITLE
Add a way to specify colors by hex code

### ISSUE THREAD

**Issue by dsizzle** [HaikuArchives/ArtPaint#256]
Most art programs seem to have a way to specify colors from a hex code; we should find some real estate in the Color palette window to add a hex code field. Perhaps shrink the color well and add the hex field below it?

**Comment by humdingerb** [comment]
Yes. While it'd fit better under the text controls of the slider volumes, that would look weird. I agree, under the the color well is fine.

**Comment by dsizzle** [comment]
I may end up rolling this in with the existing color changes… haven’t decided yet.
