### ISSUE TITLE
Accept dropped colours

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#257]
The large colour well at the right of the Colors window could accept dropped colors (and maybe also dropped text when it fits the hex format '#ffffff').
Bonus points for each color square in the palette to the left to accept the same. :)

BTW, the dropping is already working for the color wells of the main window.

**Comment by dsizzle** [comment]
You can already drop colors onto the palette.

Ad mentioned in #258 I don't understand where you can drag a hex string from and if you have an example then I can try to make that work but otherwise not sure how to even drag a string of any kind?
