### ISSUE TITLE
Remove context menu in canvas, draw bg colour instead

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#266]
Do many people use the context menu of the canvas to change tools? I kinda doubt it. The Tools window doesn't take much space and is probably always visible, if not even floating near where you paint. So mouse miles shouldn't be a big issue.

It makes more sense to use the right mouse button to use the selected tool with the background colour. That'd fit in with the usage of the RMB elsewhere in the app.

**Comment by vansh-2266** [comment]
I want to take this issue can you please explain me this? @humdingerb

**Comment by humdingerb** [comment]
Right now, if you right-click into the canvas, a context menu appears that lets you choose another tool. This ticket suggests to instead draw with the currently set backgroud colour (as opposed to the foreground colour when using the left mouse button).

Of course only for the tools where that makes sense.
Maybe for other tools different behaviour would be appropriate:
* Eraser: temporarily reverse the "Replace pixels with" setting (Background color <-> Transparency).
* Selection: temporarily reverse the "Behavior" setting (Add adrea <-> Subtract area).
* Color picker: used with the right mouse button sets the background colour.

**Comment by dsizzle** [comment]
>  I propose moving the selection itself (not translating the seletcted pixels) with the right mouse button.

but what about rotating and scaling the selection? Do you think that is less common and so not having a shorthand method is acceptable?  I wouldn’t want to try to accomplish those via modifiers to the right click.

**Comment by dsizzle** [comment]
> Eraser: temporarily reverse the "Replace pixels with" setting (Background color <-> Transparency).

the reason I didn’t do this one yet is that it felt a little off. Would anyone ever want to “erase” with the fg color if right click erases with the bg color?  And then that’s basically just painting.

**Comment by humdingerb** [comment]
> but what about rotating and scaling the selection? 

I think we need all manipulation actions - Rotate, Translate, Scale - for the selections themselves, too. I see three possibilities:
1. Create Rotate, Translate, Scale menu items in the "Selections" menu, mirroring what's under "Edit"
2. Add a checkbox "Selection only" in all manipulator windows.
3. Add another submenu-item "Selection only" where there are now "All | Active layer" submenus of Rotate, Translate, Scale in the "Edit" menu.

> Do you think that is less common and so not having a shorthand method is acceptable?

At least for me, yes. I often use a selection to delete part of an image, then move it to the next part of the image, delete, and so on.
So a shortcut for moving a selection would be very welcome.

**Comment by dsizzle** [comment]
> I think we need all manipulation actions - Rotate, Translate, Scale - for the selections themselves, too. I see three possibilities:

Yes, of course - we have #432 for this already. But I just meant as a "right-click" option for Selection.

I was planning on doing option 1:
> Create Rotate, Translate, Scale menu items in the "Selections" menu, mirroring what's under "Edit"

...though I did wonder if people could get confused thinking "well, I want to move my Selection"

I don't like #3 at all. 

The way the tools work I'm not sure if it's going to be difficult to implement moving the selection as a right-click. I plan to do the trio of translate, rotate, and scale first and then I'll see if I can figure out how to rig up translation to the right-click.

**Comment by humdingerb** [comment]
> the reason I didn’t do this one yet is that it felt a little off. Would anyone ever want to “erase” with the fg color if right click erases with the bg color? And then that’s basically just painting.

The proposal was to reverse the Eraser tool setting "bg colour <-> transparency", not "bg colour <-> fg colour".
However, I now think that would not be a good idea. If the eraser tool setup window isn't open and you see how it is set up currently, you never know what happens when you right click (which is proposed to reverse the current setting).
If you agree, I remove that proposal.

**Comment by dsizzle** [comment]
> The proposal was to reverse the Eraser tool setting "bg colour <-> transparency", not "bg colour <-> fg colour".

Yeah, i just thought that given the way the other tools work where left-click = fg and right-click = bg, then having just one tool where left = erase and right = bg might lend the question if there should be a way to make right = fg *or* bg.  

> However, I now think that would not be a good idea. If the eraser tool setup window isn't open and you see how it is set up currently, you never know what happens when you right click (which is proposed to reverse the current setting).
If you agree, I remove that proposal.

Yes, please remove it.

**Comment by humdingerb** [comment]
As you've added the above to #432 , I think this issue is resolved.
