### ISSUE TITLE
Rename build.sh -> _build.sh

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#267]
I know I should just become a better/faster typer, but can we rename build.sh?
build.sh is too long to type out and tab-completion is sabotaged by there being a "builtin" command. How about "\_build.sh" then tab-completion would kick in right after the "_" even...

**Comment by dsizzle** [comment]
I’m not a big fan of this change but then again I am quite a fast typist from years of data entry, coding, and taking notes in meetings. 😄 

Is there anything build.sh does that couldn’t be accomplished with just ‘make’?

**Comment by humdingerb** [comment]
I imagine 'make.sh' could be confusing. I do think we need some sort of script until someone more familiar with makefiles codes something up to at least separate the build of all addons and the main app and doing debug builds. I find that most useful.

Anyway, it's no biggie really. If you don't like the underscore, we just leave it as is. After all you're guy the working the most on ArtPaint.
You know what, I just duplicate the build.sh as "\_build.sh" and just have it locally.
There. sorted. :)
