### ISSUE TITLE
A more compact Colors window

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#268]
While updating the documentation, I noticed that the Colors window put on a bit of weight recently...

Before:
![windows_colors](https://user-images.githubusercontent.com/6107158/191424754-1f6c6ef6-ffa3-4358-b87f-b290c61f62ce.png)

Now:
![colors_new](https://user-images.githubusercontent.com/6107158/191424818-8b838807-ef97-4241-ba66-2bb01035deaa.png)

Some things can't be helped much, but every pixel counts in the sum of all.
Suggestions:
* make the hex field and colour well above a few pixels narrower
* less horizontal padding between slider label, value box, slider, colour well
* the old problem of the rather bigger than required value boxes...
* the minimal width of the sliders coud be reduced. In case someone only really needs to switch between colours of the palette the window can be made smaller because high slider precision isn't needed.

**Comment by dsizzle** [comment]
100%

I really should figure out those darn text boxes… there are other places they could be much smaller too.
