### ISSUE TITLE
Colors: Re-implement former modifier keys?

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#270]
Before the Colors overhaul, there were some possibly useful modifiers. The documentation says:

> If you hold CTRL while moving one slider, the others follow it, keeping their relative distance. Holding SHIFT when clicking a slider sets the other sliders to that same value.

As I'm currently updating the docs, can those features be easily re-implemented? They appear to be rather neat, if a bit hidden. Or should I remove that passage for now?

**Comment by dsizzle** [comment]
I’ll give it a try. I changed the sliders to a subclass of BSlider to both give it a more standard look but also remove a bunch of custom drawing code. The drawback is that the sliders are separate items and so I’m not sure if I can propagate a modifier click on a single slider up to the parent control. 

The CTRL one sounds weird to me but the SHIFT click sounds useful - so I’ll see what I can do.

**Comment by humdingerb** [comment]
The CTRL feature can be useful, depending on the colour model. E.g. with RGB, you could change the brightness when locking the R,G,B sliders. Not sure about other colour models. Maybe it can make sense when not locking all non-alpha sliders, but only some...
I appreciate that this would complicate things even further. :}

**Comment by humdingerb** [comment]
Discussed and partly implemented with #272.
