### ISSUE TITLE
Edit menu: move all selection items into submenu

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#285]
When put under a "Selection" submenu, use only the verbs for item label:
* Grow (ALT+G)
* Shrink (SHIFT+ALT+G)
* All (ALT+A)
* Clear (ALT+D)
* Invert (ALT+I)
* Hide border (ALT+H)

**Comment by dsizzle** [comment]
What about making a top-level "Select" or "Selection" menu?  Photoshop has a Select menu but they also have a LOT of selection options.

**Comment by dsizzle** [comment]
I do like some of them, like the ability to load and save a selection would be nice to have.

**Comment by humdingerb** [comment]
I recently also thought about save/load selections... :)
Yes to its own Selection main menu.
