### ISSUE TITLE
Freehand selections aren't smooth

### ISSUE THREAD

**Issue by dsizzle** [HaikuArchives/ArtPaint#286]
Freehand selections are not very nice with a lot of uneven edges:

![0hairy](https://user-images.githubusercontent.com/10878750/193422666-1e93701a-1755-466d-86c1-2db9273d5607.png)

They should be smooth (along pixel boundaries at least)

**Comment by Brunobasta** [comment]
they should become a blur edge or a smooth edge feature too (feather edge?)
