### ISSUE TITLE
.svg file format not supported

### ISSUE THREAD

**Issue by wei2912** [HaikuArchives/ArtPaint#29]
ArtPaint does not support scalable vector graphics.

**Comment by dsizzle** [comment]
Is this even a valid issue?  ArtPaint is pixel-based - I think Wonderbrush is the right tool for svg files.  

Unless this means a rasterized version of an svg file, this ticket should be closed imo.

**Comment by korli** [comment]
What data does the SVG translator provide? Only vectorized?

**Comment by humdingerb** [comment]
The nanosvgtranslator translates SVG to a bitmap. The DataTranslations prefs allow to set a scale from 0.2 to  10.0.  It provides what's needed for a bitmap graphics app like ArtPaint.
Closing issue, I'd say.
