### ISSUE TITLE
Button to close 'Tool settings' window is too small when the window is active

### ISSUE THREAD

**Issue by Briseur** [HaikuArchives/ArtPaint#290]
It's on nightly x64 hrev56511
Button size is good when the window is inactive (on left) but too small when the window is active (on right).
Screenshots are with Flat decorator but it also happens with the other decorators. (Haiku problem?)
It doesn't seem to happen in other windows but I only had a quick look...

![inactive](https://user-images.githubusercontent.com/37412120/193825208-20ff86d0-6390-4f5d-b572-6a5ad9a518d7.png) ![active](https://user-images.githubusercontent.com/37412120/193825260-de965e7b-c693-45e1-8109-107a4ed8488f.png)

**Comment by humdingerb** [comment]
Yep, I see this too, but alwas forgot to open a ticket...

**Comment by dsizzle** [comment]
This seems like a Haiku issue rather than something specific to ArtPaint. I don’t think the  app can control that afaik.

**Comment by Briseur** [comment]
Reported on Trac,  [ticket 11975](https://dev.haiku-os.org/ticket/17975).
