### ISSUE TITLE
No tool to pan/move a selection or layer

### ISSUE THREAD

**Issue by Brunobasta** [HaikuArchives/ArtPaint#291]
Using the text tool  you can move your text all over the canvas.
This is not possible with other selections or layer.
Would be nice to be able to move a selection with the "space"-Key to pan the selection or layer...
Press space key and move/pan the selection/layer.
Many professional programs use this.
Photoshop, illustrator, blender, in Haiku Wonderbrush.

**Comment by dsizzle** [comment]
There also is #98 for panning the canvas with Space bar.

**Comment by humdingerb** [comment]
Indeed. :)
@dsizzle: you want me to remove the space-panning from #126 again? It's not stricktly a "modifier key issue" and since it has it's own ticket... Or close #98?

**Comment by dsizzle** [comment]
Please remove it from #126 as I expect the code will be quite different than the modifiers

**Comment by humdingerb** [comment]
Done. Closing this one then as a duplicate.
