### ISSUE TITLE
Crop: use better visible frame/grabbers

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#295]
Depending on the background the frame and grabbers of the cavas cropping feature are not easily spotted:

![crop-handle-now](https://user-images.githubusercontent.com/6107158/194222983-2e710568-9373-41b1-847e-1c98a2e4d34b.png)

Instead of the alternating black&white pixels, using whole black&white lines helps. Here the selection box of WonderBrush:

![crop-handle-new](https://user-images.githubusercontent.com/6107158/194223190-4cf558a1-61da-4721-a1a3-dc41f29b4a41.png)

**Comment by dsizzle** [comment]
This can be closed due to #293
