### ISSUE TITLE
Crash when ArtP:active_layer is wrong

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#313]
Stupid ticket title...

Do this:
* Open a JPG
* Add a layer
* Close without saving
* Re-open that JPG

--> Crash: 
[ArtPaint-4706-debug-17-10-2022-06-17-59.report.txt](https://github.com/HaikuArchives/ArtPaint/files/9797444/ArtPaint-4706-debug-17-10-2022-06-17-59.report.txt)

catattr reveals that ArtP:active_layer == 1, not the expected 0.

**Comment by dsizzle** [comment]
Weird, I thought I handled that case.

related, is there a way to hand edit file attributes? I accidentally made my ducky.png unopenable by ArtPaint when futzing with the zoom levels.

**Comment by humdingerb** [comment]
In Terminal, there's addattr, just add the attribute again with the right value, or rmattr to just completely remove it. Or copyattr to copy the attribute of a working file.
DiskProbe also lets you remove attributes and edit the ones where there's a suitable editor. Numbers are no problem to edit.
