### ISSUE TITLE
RFC: Add lots more user options?

### ISSUE THREAD

**Issue by dsizzle** [HaikuArchives/ArtPaint#314]
Looking for opinions: should ArtPaint have lots more user options?  A few recent possibilities come to mind:

- Pan direction 
- Mouse wheel zoom direction 
- Mouse wheel zoom speed
- Mouse wheel zoom double or quad speed with SHIFT
- Selection line thickness
- Selection line colors

etc. etc. I'm sure there are many others.

thoughts?

**Comment by humdingerb** [comment]
No. :)
I think we should try to find the best defaults and wait on actual user input to add specific options. We can start after the next bigger release to actively ask on the forums. And even then we should try to discern if the statements are real needs of actual users, or just non-ArtPaint users listing all the options other apps have, needed or not.

My opinions on these possible optione:

* Pan direction - ArtPaint provides just one - the sane one... (the middle-mousebutton action should be changed, too)
* Mouse wheel zoom direction - Let's use what Haku apps already do. Web+, ShowImage, IOM, WonderBrush, LibreOffice... those all do zoom-in on mousewheel up. ArtPaint does it the wrong way round atm... :)
* Mouse wheel zoom speed
* Mouse wheel zoom double or quad speed with SHIFT - Lets wait until there are complaints. Possibly it can be tweaked programmatically, calculated by zoom-level  and image resolution.
* Selection line thickness - may be adjusted according to screen resolution?
* Selection line colors - as black&white ant-line, it already provides maximum contrast on all backgrounds.

All the above is of course just my opinion. As a lay-person to boot, I'm just an occasional paint app dabbler. Some of those options may make perfect sense to others..

**Comment by dsizzle** [comment]
Yeah, I agree with sensible defaults, but also think maybe instead of trying to come up with the perfect defaults, just give the user a chance to change them however they see fit.

**Comment by humdingerb** [comment]
The difficult part is to spot which setting could be contested by user preference. It's possible we hit just the right values with our defaults, or the users don't care about changing a specific setting.
Best to have user feedback to find the essential options.
Or maybe we come across something we both cannot agree on... :)

**Comment by dsizzle** [comment]
ok, closing for now
