### ISSUE TITLE
Speed up mouse wheel scrolling with SHIFT

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#317]
The mouse wheel scrolls the canvas vertically. 
CTRL+mouse wheel scrolls the canvas horizontally.
Additionally holding SHIFT should speed things up, just like it already does when zooming.

Maybe instead of a fixed speed-up (2x, 4x...?), it could scroll page-wise (like Tracker or StyledEdit), i.e. move a whole image section (minus 20% overlap so you don't lose orientation).

**Comment by dsizzle** [comment]
this can be closed as it's now moot without mouse wheel scrolling...

**Comment by humdingerb** [comment]
Right you are. Thanks!
