### ISSUE TITLE
Certain tools leave trails

### ISSUE THREAD

**Issue by hyperobject** [HaikuArchives/ArtPaint#32]
![dirt2](https://f.cloud.github.com/assets/3019167/1597268/99cc6e5a-530c-11e3-8fda-dcf9feb8e831.png)
![dirty](https://f.cloud.github.com/assets/3019167/1597269/99cf0dc2-530c-11e3-83b7-dcb98ca8ef41.png)
These trails are only cleared away by drawing shapes over/near them.

**Comment by PeteCA** [comment]
This is the result of a buggy B_OP_INVERT in Haiku (https://dev.haiku-os.org/ticket/10007).
Hopefully this will be fixed someday!

**Comment by humdingerb** [comment]
Fixed!
