### ISSUE TITLE
Color picker: Show sample size with mouse pointer

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#325]
It'd be very useful to see the area sampled with the color picker tool. To be nicely visible, I'd say a black&white dashed frame following the mouse pointer.

BTW, I do understand correctly that the set "Size" - 1 to 10 - is the side length of the sample square that the mousepointer sits in the middle of?

**Comment by dsizzle** [comment]
I assume that’s the case. I definitely agree this is needed. I thought I was experiencing a weird bug until I realized the sample size was set to 10!!
