### ISSUE TITLE
Tools window needs some form of 'focus' on the selected tool.

### ISSUE THREAD

**Issue by corihudson** [HaikuArchives/ArtPaint#33]
At the moment, you can't tell which tool you're using (other than the text at the bottom of the canvas window). It would be nice to have a border around the currently selected tool in the brushes/tools window.

**Comment by PeteCA** [comment]
I don't think this is true (these days, anyway).  The selected tool icon has a darker grey background and is slightly indented.

**Comment by dsizzle** [comment]
This already exists. Perhaps it could be made more obvious but it's there.

**Comment by korli** [comment]
can it be closed?

**Comment by dsizzle** [comment]
is it obvious enough which tool is selected?  I personally think so:

![tools](https://user-images.githubusercontent.com/10878750/162377496-9f310c1e-68ea-4faf-8513-6ab6ecbcf819.png)

**Comment by humdingerb** [comment]
IMO it's obvious which tool is selected - but only if you look a bit harder. Maybe the background of the selected tool could be darker, to catch the eye more easily.
