### ISSUE TITLE
RFC: Straight line tool to use clicks instead of dragging?

### ISSUE THREAD

**Issue by dsizzle** [HaikuArchives/ArtPaint#331]
Was wondering if the Straight Line tool should use a click for the start and a click for the end, instead of its current behavior of dragging. 

Argument for:
- would allow a "multi-line" mode where you can draw a series of connected lines. 

Argument against:
- most other tools use dragging - ellipe, rectangle, painting

**Comment by humdingerb** [comment]
I think keeping the behaviour of all tools consistent if at all possible is important.
WRT the polyline/polygon mode, it could be implemented like the intelligent scissors selection mode: the endpoint is set with a double-click. For a polygon mode, that would also connect it with the starting point.

**Comment by dsizzle** [comment]
I can't picture how polyline works in this mode, however.  

So you click to start the line, drag, then release.  How do you do the next line?  since you released the mouse to draw the first segment you have to click and drag again?  but then why not just click where you want the next endpoint? 

the intelligent scissors is not a click-drag, it's just a click to drop points and then a double-click to close it.

**Comment by humdingerb** [comment]
I blame the lack of coffee in the morning... :)
You're right, of course. 
I wonder, if we can have both:
a) mouse-down (sets start-point), drag mouse, mouse-up (sets end-point)
b) click (sets start-point), drag mouse, click (sets end-point)
I suppose the other 'geometrical' tools should make to work the same.

**Comment by dsizzle** [comment]
No wonder we are so productive - I’m looking at these late at night, long after all the coffee has worn off, while you are approaching first thing in the morning, before any coffee has had a chance to reach your brain. 🤣 

I might experiment with the “both” idea but I fear it could cause confusion.

Another idea that I thought of was having another action “drop” a point. Like keep the drag as it is now, but maybe if you click OPT or SPACE or whatever, it makes an endpoint and starts the next line?

**Comment by humdingerb** [comment]
Fully coffeinated ATM, I feel that introducing additional modifier keys makes things less discoverable. Plus memorizing keys specific to some tools isn't nice, and there's the risk of modifier collision and limiting future app-wide uses.

I more and more come to the conclusion that keeping the straight lines as is, is best. Currently it works like all other drawing tools, dragging the mouse while holding the button.

Maybe a future polyline/polygon could be a checkmark (or radio-buttons). It starts off like a normal straight line. After setting the first "segment-end-point" by releasing the mouse button, you continue to draw the next segment by dragging the mouse without holding the mouse button. The next click will set the next segment-end-point and so forth. A double click set the last end-point (or ESC will uses the last set point as end-point).
The radio-button setting determines if it's a polyline (= open polygon), or if a last line to connect to the start-point is drawn automatically. (Alternatively, the setting wouldn't be needed, if ESC would end the polyline with the last segment-end-point and a double-click would connect to the start-point, making it a polygon.)
