### ISSUE TITLE
There is no "Move selection tool"

### ISSUE THREAD

**Issue by Brunobasta** [HaikuArchives/ArtPaint#334]
If a object is selected there is no move selection tool to move it.
After creating a text it should automaticaly change to a move tool (4 arrows) to move the text around.
Try opening Wonderbrush if it is not clear yet:

choos text tool
write a text
click in the canvas to get the move/grab/transform tool.

same to other objects after you created them you can easily move the object around.

**Comment by humdingerb** [comment]
Moving things around is done with "Layer | Translate...". See also #155.
I'm not quite sure we need a separate tool for moving. Maybe click+dragging into a selection could move it (if not in "substract mode" via OPT)?

**Comment by dsizzle** [comment]
Well... text in ArtPaint definitely needs work.  Text is *not* an object that can be selected and manipulated.  Once it is created, it's just a bunch of pixels like any others.  Yes, in tools like Wonderbrush or Photoshop or GIMP, text is an object that can be selected afterward - but again, this is not the case in ArtPaint right now.

I have spent some time thinking about this and I think at some point it will need a big effort to make Text more useful.  At the very least it needs to be some kind of "object" that is not just pixels.  Maybe text needs to be put on "Text layers" that are a different kind of layer?

**Comment by dsizzle** [comment]
Actually maybe that should be the first baby step, have ArtPaint always create a new layer for text. I can’t think of any reason to not do it.

**Comment by humdingerb** [comment]
As there was an "Add text layer" item in the "Layer" menu, it was probably intended to always create a new layer for text. We removed that, however, because it didn't create a new but just called the text tool.
Anyway, +1 to have the text tool always create a new layer. People can merge layers afterwards if they want.

**Comment by humdingerb** [comment]
[stupid web+ won't let me "close with comment"]
