### ISSUE TITLE
"Select all"-selection can't be shrunken

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#336]
* ALT+A to select all
* SHIFT+ALT+G to shrink the selection

Doesn't shrink.

**Comment by dsizzle** [comment]
Yeah, the code says it inverts the selection, uses dilate, then inverts again. If that’s what it’s truly doing then of course that’ll never work if everything is selected!

**Comment by PeteCA** [comment]
Haven't commented in a while, because in general I agree!
However wrt "Select All" not being shrinkable, the current
behaviour makes sense.  I can't imagine a situation where 
you would want to shrink after selecting everything.

**Comment by PeteCA** [comment]
yeah, I suppose... (:-))  Alternatively you could just draw a rectangle
as big as possible.  Not sure it is even inconsistent -- all is all... (:-))
Not something I'd miss, anyway.

**Comment by dsizzle** [comment]
I agree with this ticket (sorry Pete) - "select all" is just a big rectangle. IMO I don't see any reason why shrinking it shouldn't work the same as any other rectangle, regardless of whether there's a use-case.

**Comment by PeteCA** [comment]
OK -- guess I'm outvoted... :smiling:  I'd just not be surprised if I ran into it.
Not really important IMV.

In any case, I should take the opportunity to pass on how impressed
I am by your continued efforts!

**Comment by dsizzle** [comment]
Thanks!  What started out as a fun side project has become an all-consuming vendetta against Adobe. 😆 

actually it’s just a fun tool with a ton of potential, so seeing it progress is addictive.

**Comment by humdingerb** [comment]
I second Pete's praise!
Hope you don't mind my constant nagging... Feel free to put your foot down, when you feel enough is enough. You do the work, you should have fun doing it.

**Comment by dsizzle** [comment]
Thanks!  I appreciate your "nagging" - without you I would've added 100 bugs to this poor code by now!
