### ISSUE TITLE
Zoom with mouse-wheel (without ALT), don't scroll canvas

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#337]
As mentioned at https://github.com/HaikuArchives/ArtPaint/issues/317#issuecomment-1285217367:

> We now have a much nicer way to scroll around the canvas - SPACEBAR panning.
Advantages:
>
> Arbitrary panning direction (versus: only vertically or - with additional CTRL - horizontally at a time)
Arbitrary panning speed (versus: max. 2 speeds (with additional SHIFT))
Allows mouse wheel zooming without holding ALT, thus freeing it for some other action.

**Comment by dsizzle** [comment]
I’m on board with this, but I thought wheel scrolling was a common Haiku thing that we wanted to keep?

**Comment by humdingerb** [comment]
I'd say it depends on the application. For Tracker or editors, wheel scrolling is natural and there are no reasonable other functions to use the wheel for. Not so graphics apps. Here we already have a nice way of scrolling (SPACE panning) and can better use the wheel for zooming. IMO.
