### ISSUE TITLE
Straight line: SHIFT when rotating overshoots endpoint

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#346]
If you create a straight line and hold SHIFT to snap to 22,5° angles, the 'predicting line' that moves with the mouse pointer overshoots its endpoint (= the mouse pointer) and hits straight into the canvas border.
Must've been introduces quite recently.

**Comment by humdingerb** [comment]
More info: All's well at 100% zoom. <100% it overshoots, >100% it undershoots.

**Comment by dsizzle** [comment]
also only happens for single-pixel lines...variable width or thick lines seem fine at all zoom levels. 

In any case I believe I fixed it.
