### ISSUE TITLE
Wheel-zoom: hit major percentages

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#352]
Currently when mouse wheel zooming, the zoom factor goes to arbitrary percentages. BTW, is displaying decimal points for the factor necessary. Feels needlessly precise...

It'd be nice if the zoom factor hits the 50%, 100%, 150%, 200% etc. zoom factors.

**Comment by dsizzle** [comment]
The little popup slider for Zoom also allows arbitrary decimal percentages.  Maybe that should also be less precise?  The slider feels fine but it's true that the zoom numbers aren't necessarily meaningful.

**Comment by humdingerb** [comment]
To be onest, I never much used the slider. I rather clicked a few times on the x/- buttons.
Also, now that we have excellent mouse wheel zooming - even honing in on the mouse poiinter - I don't see much use in the slider.
I'd be OK to remove it, but it doesn't get in the way either.

Coming to think of it: instead of the slider, a list of percentages wold be more useful when "Zoom" is clicked: maybe 25%, 50%, 100%, 200%, 300%, 400%, 600%

**Comment by humdingerb** [comment]
Fixed with #436
