### ISSUE TITLE
Fill tool: Flood + gradient = chaos

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#353]
If you set the fill tool to "Flood fill" and "Enable gradient" you an get interesting effect:

![flood-gradient](https://user-images.githubusercontent.com/6107158/198685093-edffe406-186d-4bbd-a226-b9475d67872e.png)

Selections are ignored, it always messes up the whole layer.

**Comment by dsizzle** [comment]
Is this new? I mean did this somehow break recently?

**Comment by humdingerb** [comment]
I did manage to get similar chaos with the last ArtPaint in HaikuDepot.
Before, I was able to to get this effect every time without trying. Now it's not so easy to replicate. There are other artefacts like a vertical wide line in the middle of the canvas that isn't filled, but the one described in this ticket is a bit elusive...

It seems to appear when doing the flood+gradient several times and more often when creating a second project where you do the same, and switching between them, doing fills repeatedly.

**Comment by humdingerb** [comment]
To reproduce it sometimes helps to repeatedly only drag a short distance or even just click a few times. If you manage to get these artifacts, a "Clear canvas" clears up the canvas, but the next fill will still show the artifacts.

**Comment by humdingerb** [comment]
Managed to capture it[~7MiB]:


https://user-images.githubusercontent.com/6107158/198703867-f0324980-3b5f-426e-90d6-1ecc968da226.mp4

(Github for some reason won't let me upload an MPG. You may have to rename the .MP4 to .MPG.)

**Comment by humdingerb** [comment]
Just to make sure, here uploaded off-site: http://0x0.st/o37v.mpg
