### ISSUE TITLE
Clear layer/canvas should make transparent (=remove pixels)

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#354]
Currently, invoking "Clear" from Layer or Canvas menu fills the layer/selection or canvas with the background colour. In most situations - pretty much all but if you're on the bottom layer - it's not helpful at all. And given the name "Clear", it's downright counter-intuitive.

I think it makes sense to always actually remove the pixels of the selection/layer/canvas.
People can always create a bottom-layer and fill it with their background colour.

Related: Does the "Background color" option of the Eraser tool still make sense?
Given the above, it'd more consistent to also always erase to transparent and forget about "background colour".

I think the whole "background colour" things cater to a situation where there is no transparency and layers. We do have those, though. Things sure were confusing, before you implemented the checkered-transparency indication...

**Comment by dsizzle** [comment]
I just ran into this yesterday and was going to file a ticket but forgot - in other words I definitely agree.  At the moment the ONLY way to clear a selection is with the Eraser tool, I think.  Even "Cut" fills in with the background color.  

There should also be a shortcut like Backspace or Delete for "Clear" or "Delete selected."  

Regarding the Eraser tool, I *think* I remember Photoshop having the option to Erase to background color - although I honestly can't think of a reason to use that option off the top of my head.

**Comment by humdingerb** [comment]
> There should also be a shortcut like Backspace or Delete for "Clear" or "Delete selected."

Yes, at least DEL for deleting the selected pixels, probably under "Edit | Delete". The "Clear" of whole layer or canvas are rare enough to have the users use the menu via mouse. Need to be frugal with those shortcuts...

>Regarding the Eraser tool, I think I remember Photoshop having the option to Erase to background color - although I honestly can't think of a reason to use that option off the top of my head.

Yeah could be historical reasons. And once a feature is there, it's hard to control the uprising of the users used to it. Better nip that bud while ArtPaint has few users... :)
