### ISSUE TITLE
Typo in strings

### ISSUE THREAD

**Issue by jt15s** [HaikuArchives/ArtPaint#361]
Just noticed a small typo in ArtPaint's strings whilst I was translating - 
_Not enough free memory to add a **layer .You** can free more memory by disabling the undo and closing other images. It is also a good idea to save the image now because running out of memory later on might make saving difficult or impossible. I am very sorry about this inconvenience._

This should read:
_Not enough free memory to add a **layer. You** can free more memory by disabling the undo and closing other images. It is also a good idea to save the image now because running out of memory later on might make saving difficult or impossible. I am very sorry about this inconvenience._

Thanks!

Edit: I've found another typo, this time in the Color Separator add-on:
_blac**K**_
Should probably read:
_blac**k**_

**Comment by dsizzle** [comment]
Thanks! 

The blacK one might be on purpose, to emphasize the K, since Cyan, Magenta, Yellow, and Black are abbreviated as CMYK instead of CMYB.

**Comment by humdingerb** [comment]
Exactly right with the "blacK".
I'll take care of the other typo. Thanks jt15s.
