### ISSUE TITLE
Canvas rotation with selection is inconsistent

### ISSUE THREAD

**Issue by dsizzle** [HaikuArchives/ArtPaint#379]
Steps to reproduce:

1. Create a project with 3 layers, e.g. by putting 3 different images on each layer
2. Create a selection
    a) Canvas | Rotate + 90° --> The whole canvas is rotated, instead of just the selection on all layers.
    b) Canvas | Rotate... --> Here the selection on all layers are rotated, but only on the ~~current~~ bottom  layer the selected area is cut out and rotated. On the other layers a copy of the selected area is rotated.

**Comment by humdingerb** [comment]
After I thought issue b) was gone for a moment, I figured out that it's not the current layer that is the only one behaving correctly, but always the bottom layer. Changed the ticket description accordingly.
