### ISSUE TITLE
Add DEL as shortcut for Edit > Delete

### ISSUE THREAD

**Issue by dsizzle** [HaikuArchives/ArtPaint#402]
As the title says - the DELETE key should be a shortcut for Edit > Delete.

**Comment by humdingerb** [comment]
Maybe mildly related - I'll open a separate ticket on request. :)
Can we have ESC cancel all "floating windows" like add-ons, manipulators (translate,rotate,crop,scale...) even if they don't have focus. ESC is my go-to key to cancel any current abortable action. (Would be nice for the scissors selection, too, come to think of it. It already aborts the Rectangle tool when rotating.)

**Comment by dsizzle** [comment]
Yes, ESC would be a different ticket because it's a different mechanism.  ESC is already mentioned in the manipulator UX ticket #282

**Comment by humdingerb** [comment]
Indeed.I just wanted to test your memory... Better than mine, it turns out. :)
