### ISSUE TITLE
Canvas menu: Rotate +/-90° doesn't work on selections

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#415]
All other actions - including the "Rotate..." for arbitrary angles - respect selections. "Rotate +/-90°"still always rotates the whole canvas.

**Comment by dsizzle** [comment]
This is a duplicate of part of #379 - my plan is to make the Rotate manipulator work in "headless" mode (aka without the GUI) and then remove the special case Rotate+-90 code.

**Comment by humdingerb** [comment]
Right, it's a subset off #379, so we'll close this one.
