### ISSUE TITLE
Edit menu consistency

### ISSUE THREAD

**Issue by dsizzle** [HaikuArchives/ArtPaint#418]
- Undo/Redo change to "Undo (Redo) not available" when there's nothing on the undo/redo stack.  They should just gray out instead of changing the menu item
- Cut and Copy have submenu items for "all layers" and "current layers", but Paste has "Paste as new layer" and "Paste as new project" as explicit menu items. Why not make them submenu items under "Paste"?

**Comment by humdingerb** [comment]
> Why not make them submenu items under "Paste"?

Possible. Though the other submenu-action are all "Active layer | All layers", so will be the other actions, if it's decided to move them over from the Layers menu (rotate, translate, scale...). Or we'll go with the a bit hidden" SHIFT-changes-menu" road to eliminate these submenus.

Alternatively, the function could move to File under "New project..." as "New project from clipboard".

**Comment by dsizzle** [comment]
> Alternatively, the function could move to File under "New project..." as "New project from clipboard".

not a bad idea...

**Comment by humdingerb** [comment]
Can't it be done by simply overriding the window's MenusBegging() hook change those menus' label, shortcut, message if the SHIFT keys is held?

To make it a bit more discoverable, we could add a hint to the status bar help text "...( add SHIFT for all layers)."

**Comment by humdingerb** [comment]
Pfftt, "MenusBegging()"... at least it's an existing word. The counterpart is "MenusEgging()" btw...

**Comment by dsizzle** [comment]
I tried adding the SHIFT to change to All layers and didn't really like how it felt.  Maybe if it was live it would be more compelling, but having to hold SHIFT before the menu opens feels clunky.  With removal of the "Edit > Rotate+/-90" options the menu looks clean enough in my opinion.  I'm going to close this for now.

**Comment by humdingerb** [comment]
I think you're right. Also, these commands are so ubiquitous that most users learn the "active Layer" shortcuts quickly by heart and that adding SHIFT always extends to "all layers".
BTW, I was wondering if it'd make sense to limit this to "all visible layers". What do you think?

**Comment by dsizzle** [comment]
intuitively I think that makes sense.  I feel like other tools work that way - don't operate on anything you can't see?  

I feel like that's probably an easy change. I think the "all layers" operations loop through all the layers and could just skip any that are not visible.
