### ISSUE TITLE
Transform selections

### ISSUE THREAD

**Issue by dsizzle** [HaikuArchives/ArtPaint#432]
Sometimes it's nice to take a selection and move / rotate / scale it - just the selection, NOT the image.  For example if you make a selection that is slightly off, you might want to just resize it or move it instead of undoing and redoing.  ArtPaint already has the tools to scale, rotate, and translate a selection under the hood, so this would just expose those functions to the user.

...tbh I can't think of obvious use cases that can't be accomplished other ways, but Photoshop has this ability, and as I mention, the functionality is already there.

**Comment by dsizzle** [comment]
ideas from @humdingerb:
> 1. Create Rotate, Translate, Scale menu items in the "Selections" menu, mirroring what's under "Edit"

Originally I planned to implement this because it seems most consistent, but it could be confusing to some users thinking this is how to manipulate a "selection" aka selected pixels.

> 2. Add a checkbox "Selection only" in all manipulator windows.

I don't love this idea, but it *would* be possibly less confusing, and might be easiest to implement, and the least code.

**Comment by humdingerb** [comment]
As it's related and not to be forgotten, from #266:

>> Since there's no add/substract mode (uses modifier key instead), I propose moving the selection itself (not translating the seletcted pixels) with the right mouse button.

> The way the tools work I'm not sure if it's going to be difficult to implement moving the selection as a right-click. I plan to do the trio of translate, rotate, and scale first and then I'll see if I can figure out how to rig up translation to the right-click.

**Comment by dsizzle** [comment]
After implementing the transforms, I think the right-click to move is a separate custom code path - not related to the manipulators at all.  There's no way to have the manipulator window pop up in this case, and having to click Ok or Enter to accept the move would be awkward. It'd have to accept the move when you release the right-click, which is not how other manipulators work in ArtPaint.

**Comment by humdingerb** [comment]
You're right! I haven't thought about that...

BTW, one thing I do very often in Photoshop is to clone the selection (i.e. the selected pixels of course) by holding AltGr and moving a selection. Possible? Just something to keep in the back of your head... together with SHIFT restricting horizontal/vertical movement. Getting a bit much for the back of the head... :)

**Comment by dsizzle** [comment]
Not sure what you mean by “clone” the selection… like the clone tool, painting with the selection?

**Comment by humdingerb** [comment]
Not painting reall. Instead of moving (=translate) the selected pixels, you copy them (on the same layer) to where you release the mouse button.
