### ISSUE TITLE
Preferences window size for languages other than English

### ISSUE THREAD

**Issue by victroniko** [HaikuArchives/ArtPaint#437]
Hi there. Sometimes captions get cut in the Preferences window when using languages other than English (w/longer sentences). This also causes some controls to shift to the right and partially hide.

As it seems this window isn't dynamically-sized and there is plenty of room, is it possible to enlarge it a bit to accommodate these edge cases?

![ap1](https://user-images.githubusercontent.com/67852064/207676129-c8db4a67-aa7c-44cc-807e-623415a7ba61.PNG) ![ap2](https://user-images.githubusercontent.com/67852064/207676142-5efe2720-3327-424a-999f-b1033e0247ae.PNG)

**Comment by humdingerb** [comment]
I thought that one was fixed and buried already, see #230...
@dsizzle, get the shovel, I think the zombi apocalypse is here...

**Comment by victroniko** [comment]
Grawr. Another one in _Image > Resize_ window.

![image](https://user-images.githubusercontent.com/67852064/207907813-cb10028b-c782-43e8-9adc-a31362dc3b86.png)

**Comment by dsizzle** [comment]
@humdingerb do you know if we released since #230 was fixed?

@victroniko which part is cut off in the Resize window? That window has been reworked in the latest code and so I will make sure it works before next release

**Comment by victroniko** [comment]
@dsizzle I was just showing the slightly misaligned width/height input boxes, stemming from the same thing -- longer words/sentences in translations "shift" controls to the right. For example, width is _larghezza_ in Italian and _szerokość_ in Polish, those two push this box even further.

My point being: enlarging some windows (like Settings) and/or separating controls a bit more will make room for longer texts, this would avoid cases like these and give a more uniform UI feeling.

**Comment by dsizzle** [comment]
@humdingerb not sure when/how it happened, but the code change in #244 is not present in master.

**Comment by humdingerb** [comment]
#438 applied, though the original #244 was definitely applied as it's in `git log` output: 
```
commit f42a759d7758c3757b4cb2db5364a4798adeecbe
Author: Dale Cieslak <dcieslak@yahoo.com>
Date:   Fri Aug 5 10:45:02 2022 -0700
```
Maybe some later PR reverted unadvertedly. Anyway, I don't plan to get all Sherlock on it...
