### ISSUE TITLE
Crash with filtered canvas scaling

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#448]
After #445, scaling the canvas crashes: 
[Uploading ArtPaint-17029-debug-26-12-2022-08-15-16.report.txt…]()

**Comment by dsizzle** [comment]
I can't repro this so far, and the link above seems to just link to this ticket instead of a report.

**Comment by humdingerb** [comment]
Weird, crashes on every canvas resize...
Hope this report is OK, otherwise stupid Web browser can't upload...:

[ArtPaint_debug-5466-debug-26-12-2022-17-00-41.report.txt](https://github.com/HaikuArchives/ArtPaint/files/10304208/ArtPaint_debug-5466-debug-26-12-2022-17-00-41.report.txt)

That's a debug build. When debugging in Debugger instead, this is where its stuck:

![Debugger](https://user-images.githubusercontent.com/6107158/209571027-96963419-a0c2-46fa-bd45-78a20dd8cc3e.png)

**Comment by grexe** [comment]
I get the exact same crash now everytime I resize the canvas, same crash log (attached mine below as reference anyway).
To go sure, I'll attach a small test image as well.
Using ArtPaint 2.7.1 and Haiku nightly hrev58760 from today.
```
Debug information for team /boot/system/apps/ArtPaint/ArtPaint (4899):
CPU(s): 8x Intel 11th Gen Core™ i7-1165G7
Memory: 31,85 GiB total, 6,80 GiB used
Haiku revision: hrev58760 Mar 19 2025 06:02:19 (x86_64)

Active Threads:
	thread 4899: ArtPaint (main)
	thread 4928: w>(*) Untitled - 1 | (kdl-nfs4- 
	thread 4930: w>Tools 
	thread 4942: ImageView thread 
	thread 4943: team 4899 debug task 
	thread 4941: ImageView thread 
		state: Exception (Segment violation)

		Frame		IP			Function Name
		-----------------------------------------------
		0x7fcb00be3fe0	0x1703b3d4fa8	ScaleUtilities::ScaleHorizontally(float, float, BPoint, BBitmap*, BBitmap*, float, interpolation_type) + 0xe68 
			Disassembly:
				ScaleUtilities::ScaleHorizontally(float, float, BPoint, BBitmap*, BBitmap*, float, interpolation_type):
```

**Comment by grexe** [comment]
test image is ironically another bug;-)
![Image](https://github.com/user-attachments/assets/aff85b0d-cd9f-436e-bdff-824000d40f73)

**Comment by humdingerb** [comment]
I resized your test image without crash on current Haiku Beta5, 64bit.
Set to 50%, locked, bilinear. Do you have a Beta5 to test if it crashes there, too?

**Comment by grexe** [comment]
which version of ArtPaint is shipped with beta5? I could try to run that on  my nightly...
I would also have a spare Haiku partition I could use if that doesn't work out.

**Comment by humdingerb** [comment]
ArtPaint isn't shipped with Haiku releases. I run the current version, v2.7.1.
