### ISSUE TITLE
Convert to the layout API

### ISSUE THREAD

**Issue by waddlesplash** [HaikuArchives/ArtPaint#45]
This will fix a lot of the sizing issues.

**Comment by dsizzle** [comment]
I think the main two items left are:

- Layers window
- Colors window

**Comment by dsizzle** [comment]
I think this ticket can be closed, no?  The only item I'm aware of that is not-layout-savvy is the Save file panel, but that's not a LayoutAPI thing (rather unfortunately).

**Comment by humdingerb** [comment]
Yay! \o/

**Comment by dsizzle** [comment]
I appreciate the cheer emoji \o/ but can we also close this issue?  I like seeing the ticket numbers go down. :laughing: 

\o/ \o/ \o/ 

¯\_(ツ)_/¯

**Comment by humdingerb** [comment]
It's of course all Web+ fault. :) Merged PRs appear to be still open but arent't, and closing an issue either doesn't work at all, or you're not sure if it's actually closed. I apparently forgot to double-check that with the phone. Doing that now...
