### ISSUE TITLE
add-ons menu is empty

### ISSUE THREAD

**Issue by bbjimmy** [HaikuArchives/ArtPaint#46]
hrev 48494 atfer installing ArtPaint 2.1 hpkg, the add-ons menu is empty. one cannot shange the color balance. brightness or contrast of an image.

**Comment by CodeforEvolution** [comment]
This should be closed since the ArtPaint recipe was updated for my addon fixes and has been added as a package option at least to x86_gcc2

**Comment by humdingerb** [comment]
Right, thanks. There's still #48 of course.

**Comment by CodeforEvolution** [comment]
Right, thanks by the way for updating the recipe! I've been very busy so it helps!
