### ISSUE TITLE
Scaling whole layer crashes

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#476]
* Open an image
* ALT+E to scale
* Enlarge by changing the sclae-box with the mouse and click OK or press ENTER.

-> crash:  [ArtPaint-1552-debug-20-02-2023-10-27-13.report.txt](https://github.com/HaikuArchives/ArtPaint/files/10783471/ArtPaint-1552-debug-20-02-2023-10-27-13.report.txt)

Only happens if you enlarge up-wards, i.e. the top grabbers get a negative Y coordinate. Enlarging downwards by dragging one of the bottom grabbers doesn't crash. Neither when enlarging only to the left/right.
No crashes when a selection is in play, even if you ALT+A (select all).
Funnily, entering "-10" in the "Top" text box of the Scale window doesn't result in a crash when applied.

**Comment by dsizzle** [comment]
Good find! Not sure how this escaped before...

> Funnily, entering "-10" in the "Top" text box of the Scale window doesn't result in a crash when applied.

If you _only_ enter -10 in the "Top" box then it's just a translation. If you move the bottom down as well, it crashes.
