### ISSUE TITLE
Invert selection bug

### ISSUE THREAD

**Issue by dsizzle** [HaikuArchives/ArtPaint#479]
Not working after select-> all non selected ?

need to test more

**Comment by humdingerb** [comment]
Not sure what you mean.
* Select all (ALT+A)  --> all is selected
* Invert (ALT+I) --> none is selected

Seems to be correct, no?

**Comment by dsizzle** [comment]
Ha. I typed this on my phone right before I went to bed. It should say Select > All non-transparent.

**Comment by dsizzle** [comment]
...and it seems like it works sometimes but not others?

**Comment by dsizzle** [comment]
No good:
![inv01](https://user-images.githubusercontent.com/10878750/221365910-88e271d1-fcb6-46ad-8819-1c09982dd2b2.png)
![inv02](https://user-images.githubusercontent.com/10878750/221365914-4d1dcf6e-ef96-418d-9c02-49f90efe7c95.png)

but Walter works fine:
![inv03](https://user-images.githubusercontent.com/10878750/221365919-90859e9e-e57b-48c6-b276-80df0b5997ef.png)
![inv04](https://user-images.githubusercontent.com/10878750/221365924-68bcd42a-aae7-4f09-810b-4d5f08866c9f.png)

**Comment by humdingerb** [comment]
FWIW, I tried now for a bit but couldn't reproduce...

**Comment by dsizzle** [comment]
Yeah, not a showstopper for release but I wanted to record it and see if I can figure out what’s going on. Seems like if I invert a second time it works, which makes zero sense. Maybe it’s just a drawing issue somehow, or related to zoom level?
