### ISSUE TITLE
About Window shows wrong version?

### ISSUE THREAD

**Issue by dsizzle** [HaikuArchives/ArtPaint#489]
I'm *positive* this is version 2.5, but the About window shows 2.2

![artp22](https://user-images.githubusercontent.com/10878750/222942569-8a27cc8f-1eb1-4895-9c82-51b9df542a53.png)

I tried deleting the settings and it still shows 2,2.

**Comment by humdingerb** [comment]
I bet you got some old v2.2. ArtPaint tucked away somewhere. The AboutWindow uses a query for the app signature and picks the wrong one.
BTW, you can use QuickLaunch to look for all ArtPaint binaries (maybe even activate "Show version" in its settings) and do a CTRL+Enter on a version you want to remove. Opens its parent folder in Tracker and you can quickly delete it there.

**Comment by dsizzle** [comment]
ah ok, I do have an old version right on my Desktop.  Removing that resolves this issue. It'd be nice if it found the appropriate one, but such is life.
