### ISSUE TITLE
Don't store identical brushes

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#502]
If there's already a brush stored with identical settings, don't store an additional copy.

Additionall, the existing brush could be moved to the end of the list of brushes; the user may expect newly stored brush to appear at the end of the list.
Or, just move the selection to the already existing brush. (BTW, the selection isn't very visible. I'll create another ticket...)

**Comment by dsizzle** [comment]
additional idea: when a brush is first selected, gray out the "Store Brush" button until something is changed.
