### ISSUE TITLE
x86 build broken

### ISSUE THREAD

**Issue by korli** [HaikuArchives/ArtPaint#544]
rtpaint/layers/Layer.cpp: In static member function 'static Layer* Layer::readLayer(BFile&, ImageView*, int32, bool, int32)':
artpaint/layers/Layer.cpp:496:41: error: cannot convert 'uint64*' {aka 'long long unsigned int*'} to 'uLongf*' {aka 'long unsigned int*'}
  496 |                                         &actual_length,
      |                                         ^~~~~~~~~~~~~~
      |                                         |
      |                                         uint64* {aka long long unsigned int*}
In file included from /boot/system/develop/headers/x86/zlib.h:34,
                 from artpaint/layers/Layer.cpp:31:
/boot/system/develop/headers/x86/zlib.h:1267:32: note:   initializing argument 2 of 'int uncompress(Bytef*, uLongf*, const Bytef*, uLong)'
 1267 | ZEXTERN int ZEXPORT uncompress OF((Bytef *dest,   uLongf *destLen,
      |                                ^~
artpaint/layers/Layer.cpp: In member function 'int64 Layer::writeLayer(BFile&, int32)':
artpaint/layers/Layer.cpp:639:25: error: cannot convert 'uint64*' {aka 'long long unsigned int*'} to 'uLongf*' {aka 'long unsigned int*'}
  639 |                         &dataLengthCompressed,
      |                         ^~~~~~~~~~~~~~~~~~~~~
      |                         |
      |                         uint64* {aka long long unsigned int*}
In file included from /boot/system/develop/headers/x86/zlib.h:34,
                 from artpaint/layers/Layer.cpp:31:
/boot/system/develop/headers/x86/zlib.h:1229:30: note:   initializing argument 2 of 'int compress(Bytef*, uLongf*, const Bytef*, uLong)'
 1229 | ZEXTERN int ZEXPORT compress OF((Bytef *dest,   uLongf *destLen,
      |                              ^~

**Comment by dsizzle** [comment]
well, dang it.
