### ISSUE TITLE
Brush aspect oddness when storing a brush 

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#546]
Configure a brush, e.g.:
Size: 50
Aspect: 5.00
Angle: 40
Hardness: 45

Store brush. See the Aspect change to -5.00

Now switch to some other brush, then back again to the just stored one. The aspect is now -5.00, the preview pane shows the same shape as when you've stored the brush (i.e. aspect 5.00).
Now move any slider a tiny amount. -> The preview jumps to show the actual aspect -5.00, i.e. 90° rotated from the 5.00 setting.

**Comment by dsizzle** [comment]
Thanks for this - I've seen it and keep forgetting to file a bug!
