### ISSUE TITLE
Brush size oddness when entering a value

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#547]
If you enter a size value in the text box and hit ENTER, the size is applied correctly.
~~If you enter it and use TAB to move the focus to the slider, the value decreases by one.~~
If you enter it, press ENTER, and use TAB to move the focus to the slider, the value decreases by one.

That's unique to the Size slider, all others behave correctly.

**Comment by humdingerb** [comment]
I retried this after applying #550.
First thought is was fixed, but I either misreported previously, or it has subtly changed. I edited the ticket to reflect the change.

**Comment by dsizzle** [comment]
yeah, I knew it wasn't fixed by #550 - I saw it happen when I was debugging that.
