### ISSUE TITLE
Crop: width and height 1 pixel off

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#552]
As an example, get this image of the Deskbar: 
![screenshot1](https://github.com/HaikuArchives/ArtPaint/assets/6107158/f5d46e54-6bdc-4ff7-a11b-ff8e26ee42e3)
* Zoom into the top right corner
* Open "Crop..."
* Enter Top = -1 and Width =188 - which should add a pixel to the top and left
--> Works as expected for the top, but adds 2 pixels to the right
Opening the Crop dialog again, truthfully shows a width of 189.

Similarly when adding to the height:
* Enter Left = -1 and Height = 268 - which should add a pixel to the left and bottom
--> Works as expected for the left, but adds 2 pixels to the bottom
Opening the Crop dialog again, truthfully shows a height of 269.

An off-by-one somewhere.

**Comment by dsizzle** [comment]
I thought we had this issue back when I re-did the Crop and we shook out all these off-by-ones... :frowning_face:

**Comment by humdingerb** [comment]
Let's hope it's not like the bindweed in my garden or it'll keep cropping up no matter what you do... :)

**Comment by dsizzle** [comment]
> it'll keep cropping up 

Nice one!  Do you have any kids?  This is a great "dad joke"... 

"Problems with resizing images just keep *cropping* up"

**Comment by humdingerb** [comment]
While I'm often 'complimented' on my dad jokes, I don't have eye-rolling teenagers that would complete the scene... :D

**Comment by dsizzle** [comment]
Fixed by #630
