### ISSUE TITLE
Consider updating About Window to use BAboutWindow

### ISSUE THREAD

**Issue by scottmc** [HaikuArchives/ArtPaint#57]
The About Window needs cleaning up.  During this clean up it might make sense to convert it over to make use of BAboutWindow.

**Comment by humdingerb** [comment]
You wanna remove the scroller?! But it's so adorably 90s... :)
Personally, I'd keep it. The BAboutWindow looks quite hideous IMO.

**Comment by digib0y** [comment]
I can work on this one however only if @humdingerb has no issue with BAboutWindow ;)

**Comment by PeteCA** [comment]
I also rather like the scroller!

**Comment by scottmc** [comment]
Let's keep the scroller then.  Just update the text as you see fit on the pending pull-request.
