### ISSUE TITLE
Pressing DEL during selection transfomation gives unexpected results

### ISSUE THREAD

**Issue by dsizzle** [HaikuArchives/ArtPaint#570]
Steps to reproduce:

1. Select something
2. Choose Selection->Translate  and move the selection, but do NOT accept the move
3. Press DELETE

Expected results: 
- nothing happens, or
- DELETE cancels transformation, or
- DELETE causes transform to be applied and then the deletion occurs

Actual results:
- Deletion occurs in previous position of selection, and transformation is still active:
![selbug](https://github.com/HaikuArchives/ArtPaint/assets/10878750/c98c103f-10a7-4bd9-8f74-fa2ba6103fb9)

**Comment by humdingerb** [comment]
I'd opt for "DELETE causes transform to be applied and then the deletion occurs".
