### ISSUE TITLE
Undo of Selection->Invert doesn't work properly

### ISSUE THREAD

**Issue by dsizzle** [HaikuArchives/ArtPaint#571]
Steps to reproduce:

1. Make a selection with a hole in the center
2. Choose Selection->Invert
3. Choose Undo (ALT + Z)
4. Choose Selection->Grow a few times

Expected results:
![sel-grow1](https://github.com/HaikuArchives/ArtPaint/assets/10878750/e26747fe-2d07-476d-97b1-3f41ab2e8c1d)

Actual results:
![sel-grow2](https://github.com/HaikuArchives/ArtPaint/assets/10878750/ea2750bc-3c66-47d7-90ad-9bffae89edda)

... for some reason the Undo of the Invert selection loses the hole in the center.  If you don't Undo, but rather just Invert again, it works fine.

**Comment by dsizzle** [comment]
ugggh.... this appears to have been broken with #526 - and it appears that holes in selections are not treated properly, which is why they get lost, not just in this case.  

For example:
1. Load Walter image
2. Select all non-transparent
3. Ctrl+Alt+T to Translate it, hit Ok
4. Fill the selection and note that the gaps between the letters got filled, but they shouldn't.

**Comment by humdingerb** [comment]
Uh oh, a topological embarrassment. Holy moly. Looks like Mr. Moore of #526 wasn't wholly correct...

**Comment by dsizzle** [comment]
Well, I don't blame him. I should've done moore testing...

**Comment by humdingerb** [comment]
Nice one! 😃
