### ISSUE TITLE
Straight line tool: No undo

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#585]
The straight line tool can't be undone... I think it used to work. No idea when it broke.

**Comment by dsizzle** [comment]
Seems like it is broken with "Use current brush" but without the brush it's fine

**Comment by humdingerb** [comment]
FWIW, here the undo item only appears when activating "Adjustable width". With any other setting, there's no "Undo".

**Comment by dsizzle** [comment]
I believe you. I only tested it quickly and I had "Adjustable width" selected.
