### ISSUE TITLE
Straight line: Antialiased 1px lines look funny

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#586]
See a 1px line - antialiased at the top non-antialiased below (200% zoom):

![screenshot1](https://github.com/HaikuArchives/ArtPaint/assets/6107158/ebd75d36-0632-4937-bd63-a1eec85f40d4)

Here with a 400% zoom:

![screenshot2](https://github.com/HaikuArchives/ArtPaint/assets/6107158/de1ca33e-9e10-4d18-b807-ec9359385558)

For comparison, 1px line in WonderBrush:

![screenshot3](https://github.com/HaikuArchives/ArtPaint/assets/6107158/5ff2b2fa-7482-48b8-ab84-85dd93a1fa7a)

**Comment by dsizzle** [comment]
Yeah, I think the 1px lines are just too aggressively anti-aliased.

**Comment by dsizzle** [comment]
I marked this as a "bug" because I think maybe the anti-aliasing algorithm isn't quite right.
