### ISSUE TITLE
Add-on "Color reducer": "Preserve solids FS" broken

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#614]
Something's wrong when choosing "Preserve solids FS" in the COlor reducer add-on:

![colorreduce](https://github.com/HaikuArchives/ArtPaint/assets/6107158/d4038df8-c74d-458c-8871-51147f1764b4)

**Comment by dsizzle** [comment]
should be interesting. I have no idea how any of that code works.

**Comment by humdingerb** [comment]
Something's wrong... Invoking any addon crashes with 
[ArtPaint-6941-debug-08-11-2023-06-32-44.report.txt](https://github.com/HaikuArchives/ArtPaint/files/13293039/ArtPaint-6941-debug-08-11-2023-06-32-44.report.txt)
