### ISSUE TITLE
Text tool: its features doesn't work

### ISSUE THREAD

**Issue by Giova84** [HaikuArchives/ArtPaint#62]
I'm running the last available release 2.1.1 of ArtPaint and I've found these features of the Text tool, which doesn't works:

- If i add a Text field, it doesn't apply the color which I previously choosed from the color palette (and however seems that there is no way/option to change the color of text?)
- If I attempt to change the size of text from the dedicated slider (which is present inside the Text tool option window, where I can change the font and so on), this doesn't have any effect on the text: it will remain always of the same size; is the same for "rotation" and "shear" sliders: all the sliders inside Text tool window are not applied at all. 
- Furthermore if I select the checkbox (apply Anti-Aliasing) I don't see any difference: some fonts still looks sharpened.

**Comment by PeteCA** [comment]
> If i add a Text field, it doesn't apply the color which I previously choosed from the color palette (and however seems that there is no way/option to change the color of text?)

It looks as if the text is always black until you change a slider in the Palette window, at which point the colour of the "active" text will change appropriately.  Not really what you want though.

The Text parameter panel is certainly inactive.  (I see it worked in the 2008 version, so maybe not too hard to locate.)

**Comment by PeteCA** [comment]
OK -- I've solved this one.  Turned out to be a simple glitch in the NumberSliderControl.  Another mistake in the same 10-line function was causing an annoyance with the Brush tool in that whenever one changed the brush parameters, the brush went inactive until the brush-image window was clicked.  I'll do a PR once I've cleaned up a few other things.

**Comment by PeteCA** [comment]
Fix committed #66  Please close.
