### ISSUE TITLE
Transparency tool doesn't work

### ISSUE THREAD

**Issue by Giova84** [HaikuArchives/ArtPaint#63]
ArtPaint 2.1.1:
I'd like to make a transparent layer, so I choose the transparency tool: it said: "Press the mouse button to adjust layer's transparency"): the only thing that happen, when I attempt to use this tool, is that ArtPaint will use the whole CPU (as I can see from ProcessController in the Deskbar) and no trasparency is applied.

EDIT:
If i open a PNG file with a transparent background, in ArtPaint this transparent background is replaced with a white color. Seems that ArtPaint doesn't support the alpha channel/transparency?

**Comment by PeteCA** [comment]
> 'd like to make a transparent layer, so I choose the transparency tool:

Don't use the "Transparency Tool" to change the alpha of an entire layer.  The "Change Transparency..." item in the Layers menu works well for this.

The action of the Transparency Tool is rather confusing.  It adjusts the transparency of the area being painted to the _current_ alpha value in the Palette window, so if you've been painting with an opaque colour you won't see any transparency appear.

> If i open a PNG file with a transparent background, in ArtPaint this transparent background is replaced with a white color. Seems that ArtPaint doesn't support the alpha channel/transparency?

Yes, ArtPaint fully (now!) supports the alpha channel.  It just doesn't show it clearly.  Any transparent area will show as white, even though its alpha is zero (it was the same in BeOS).  This is something I dearly wanted to improve but had no success.  Don't know what I'm missing -- background layer didn't work,changing drawing mode to B_OP_ALPHA just made a mess.  Investigations welcome.

**Comment by dsizzle** [comment]
I have a decent version of this working, but still fiddling with some parts of it.
