### ISSUE TITLE
Undocumented Add-Ons

### ISSUE THREAD

**Issue by PeteCA** [HaikuArchives/ArtPaint#65]
There are several add-ons that apparently never appeared in the manual.  They should get entries there.

They are:
 AHE = Adaptive Histogram Equalization
 ColorSeperator = ColorSeparator
 AntiDitherer (...)
 Detects Edges
 Enhance Edges
 Gaussian Blur (...)
 Interference (...)
 Marble
 PolarMapper
 Reducer (...) [Currently not in the set]
 Sharpness (...)
 Threshold (...)

Most are probably intuitive, but could do with a brief note.  (And I'd love to know exactly what "Adaptive Histogram Equalization" is exactly!)

**Comment by twse** [comment]
Please close this issue - all the add-ons appear documented.

**Comment by humdingerb** [comment]
Indeed.
