### ISSUE TITLE
Artpaint crashes in Save-as file panel

### ISSUE THREAD

**Issue by clasqm** [HaikuArchives/ArtPaint#67]
Specifically when calling ClipDinger. To replicate:

- Launch a graphic in Artpaint 
- scale it (or edit it some other way, I suppose) 
- click File | Save Image As ... 
- click in the text field where a new filename is to be supplied.
- Activate Clipdinger with SHT-ALT-V 
- double-click on Clipdinger item

This sequence of actions consistently crashes Artpaint in hrev51065, using the versions of Artpaint and Clipdinger in the hrev.

**Comment by humdingerb** [comment]
It's crashing for me as soon as as I press SHIFT+ALT+V, see also the closed ticket https://dev.haiku-os.org/ticket/13442

Are you sure Clipdinger plays a role here? I uninstalled Clipdinger, even rebooted, and a SHIFT+ALT+V in ArtPaint's save-as filepanel still crashes.

**Comment by clasqm** [comment]
No, after your very scientific investigation I think we can leave Clipdinger off the hook <g>. I just have no other reason to press that particular key combination.

**Comment by humdingerb** [comment]
My mind must've blanked... I reported just that a year ago: https://dev.haiku-os.org/ticket/12721
It's not just ArtPaint, but any file panel...
