### ISSUE TITLE
Selection area is blacked out (Beta 2)

### ISSUE THREAD

**Issue by PeteCA** [HaikuArchives/ArtPaint#80]
Running ArtPaint in Beta 2, any area selected (with any method in the tool) goes totally black, which rather makes the selection completely useless!  The package downloaded from HaikuDepot is artpaint-2.1.2-2-x86_gcc2.hpkg, but I don't see any code changes in the app since before beta 2, so I imagine some change to Haiku itself has screwed things. (I tried the version I have in beta 1 that works properly there, but I get "missing symbol" in beta 2.)

**Comment by dsizzle** [comment]
This still seems to be present in the 32-bit version, but not 64-bit

**Comment by dsizzle** [comment]
Is this still an issue?  I'm not seeing it with my 32-bit nightly.

**Comment by humdingerb** [comment]
Me neither.
