### ISSUE TITLE
Make BlurAddOn apply effect live

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#89]
Other addons apply their effect live while moving the slider knob. For some reason it's not done for the Blur addon. It appears that simply uncommenting line 599 would do the trick:
https://github.com/HaikuArchives/ArtPaint/blob/master/addons/AddOns/Working/BlurAddOn/Blur.cpp#L599

**Comment by dsizzle** [comment]
Can you test this again?  It works 'live' for me as I move the slider on the current master.

**Comment by dsizzle** [comment]
never mind, I get it - you mean without letting go of the slider.
