### ISSUE TITLE
Interference addon setup window has no controls

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#90]
Interference addon setup window has no controls:

![interference](https://user-images.githubusercontent.com/6107158/160274225-aa8812d9-3639-41f6-a219-8f3e8287ebed.png)

**Comment by dsizzle** [comment]
This isn't a bug per se - the Interference Add-on actually doesn't expose any controls to the user.  It's all commented out and therefore working as designed.   

that said, this add-on could be enhanced to display both the center points as X,Y coordinates so they could be tweaked manually, as well as letting the user dynamically adjust the wavelengths of the pattern.

**Comment by humdingerb** [comment]
Right. Until then, maybe the same text as for the "Text tool" could be shown: "No configuration options available."

Generally, maybe every setting that is now only set via a slider between "low" and "high" should have an additional text control to set a specific value. A user may also want to apply some add-on on several layers/projects with the same value, which is a bit dificult atm.

**Comment by dsizzle** [comment]
Looked at this again and I agree it's a bug - an add-on with no controls should actually be a Manipulator instead of a WindowGUIManipulator.  However, as I mentioned before, I believe this add-on SHOULD have options and I am going to add some.

**Comment by humdingerb** [comment]
Even better. :)
