### ISSUE TITLE
Reducer addon crashes when changing palette mode

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#91]
Changing the "Palette mode" from "BeOS palette" to "GLE palette" crashes ArtPaint:

[ArtPaint-5834-debug-27-03-2022-08-53-17.report.txt](https://github.com/HaikuArchives/ArtPaint/files/8357233/ArtPaint-5834-debug-27-03-2022-08-53-17.report.txt)

**Comment by dsizzle** [comment]
Confirmed the bug, and the fix is not immediately obvious - will take some digging
