### ISSUE TITLE
Layers window: wrong sized scrollbar

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#99]
The scrollbar of the "Layers" window doesn't fill the height of the window:

![layers-scrollbar](https://user-images.githubusercontent.com/6107158/160294146-338fd2fa-b258-4935-bc88-545930341bce.png)

**Comment by dsizzle** [comment]
I think this is arguably correct. The top image isn't a Layer, but rather the composite of all active layers.

**Comment by korli** [comment]
> I think this is arguably correct. The top image isn't a Layer, but rather the composite of all active layers.

Shouldn't the scrollbar fill from the bottom though?

**Comment by dsizzle** [comment]
Yes.  My bad.  I guess I am tired and didn't notice the bottom arrow.  Ignore my comment - this is definitely a bug.

**Comment by PeteCA** [comment]
On Sun, Mar 27, 2022 at 07:26:53PM -0700, Dale Cieslak wrote:
> I think this is arguably correct. The top image isn't a Layer, but rather the composite of all active layers. 
> 
I think Humdinger's point is that the scrollbar doesn't extend all the way to
the bottom of the window.  I don't see any reason why it shouldn't, and
I guess the longer the better.
.

**Comment by PeteCA** [comment]
On Sun, Mar 27, 2022 at 09:33:50PM -0700, Dale Cieslak wrote:
> Yes.  My bad.  I guess I am tired and didn't notice the bottom arrow.  Ignore my comment - this is definitely a bug.
> 
Sorry -- I should read all replies before replying (via email) myself!
